### ISSUE TITLE
[feature request] up arrow searches history for matching start of line

### ISSUE THREAD

**Issue by jsbain** [ywangd/stash#103]
I think this is how real bash works?  If I type `gi` then up arrow  history would be load line that started with `gi`, maybe my last git command for example.

**Comment by ywangd** [comment]
I believe this is how iPython behaves not Bash, but it is a good feature to add. I'll work on it.

**Comment by ywangd** [comment]
By the way, you can type `!gi` and just hit enter to re-execute the last git command, just like how you can do it with Bash.

**Comment by ywangd** [comment]
This feature is now added 70181e1eca629640fd372eb75d294966150b8e52
Please let me know how it works for you.
