### ISSUE TITLE
CC (Control-C) confuses `raw_input`

### ISSUE THREAD

**Issue by oefe** [ywangd/stash#108]
Pressing the `CC` button during `raw_input` in a command terminates the command as expected. However, afterwards `raw_input` calls in future runs of the command get mixed up.

## Test command ##

```python 
first = raw_input('first: ')
print ('first = {}'.format(first))
second = raw_input('second: ')
print ('second = {}'.format(second))
third = raw_input('third: ')
print ('third = {}'.format(third))
```

## Example runs ##
```
~/Documents]$ test_raw.py 
first: alpha
first = alpha
second: beta
second = beta
third: gamma
third = gamma
[~/Documents]$ test_raw.py
first: aleph
first = aleph
second: stash: successfully terminated thread <Thread(_shruntime_thread, stopped daemon 324108288)>
[~/Documents]$ test_raw.py
first: Alice
second = Alice
third: Bob
third = Bob
[~/Documents]$ 
```

The first (uninterrupted) run works as expected.
Also, the second run (interrupted at the second prompt) seems to terminate fine.
However, the third run (uninterrupted again) behaves strange:
- where is the output of the first `print` gone?
- also, where is the second prompt?
- and why does the second `print` print what I entered at the first prompt?

This is in the `dev` branch, btw.

**Comment by ywangd** [comment]
This is unfortunately not something I can fix. This is because there is no proper way to terminate a thread from another thread. StaSh does it by simply call the running thread's `_Thread_stop()` method. This method simply ends a thread without any guarantees, e.g. it does not trigger any `try` block and it does not attempt to close any open I/O, which is the cause of your problem. The `raw_input` I/O is still open and waiting for user input after the thread is terminated. 

This issue can be alleviated if there is a way raise Exception from one thread in the context of another thread, which seems to be impossible without resorting to `ctypes`. Even we can do that with the next Pythonista release that includes `ctypes`, I am not sure if this can help with the I/O blocks. 

More discussion can be found here https://github.com/ywangd/stash/issues/16#issuecomment-67734113

**Comment by jsbain** [comment]
I wonder if we could create a custom raw_input function which checks if the thread was stopped before returning results.

**Comment by ywangd** [comment]
@jsbain This is a brilliant idea! 

It prompted me to think that all input requests via the terminal are in fact delegated by the ShTerm object. So no matter what kind of input function is used, be it `raw_input()` or `read()`, they all call ShTerm to get the input, that is, read functions of ShTerm are called in the same of thread of running commands. So I can actually flag ShTerm to raise a Simulated Keyboard Interrupt exception so input requests can be terminated gracefully. 

The changes are pushed as 91a9212893a1d44223179d5be99a4ebe63b79c23
I had some basic tests and it seems to work fine. 
@oefe Please let me know how it works for you.

Please note that it only handles input requests via StaSh terminal. If input requests are waiting for a file or a socket, pressing `C-C` will still have the same issue.

**Comment by jsbain** [comment]
Wonderful!  I tried it, and worked great.
One question... DId cat always require two ctrlDs to end input mode?  Not sure if that behavior broke here, or if it was always that way?

**Comment by ywangd** [comment]
@jsbain That is a very keen observation. No, `cat` used to require only one C-D to end input mode. However, after this change e9949727ca37fefb9bfa8f2484279313ebdacd9e , the `fileinput.input()` method always requires two taps on C-D to end the input. It only affects this method, other input calls such as `raw_input()` does not have this issue. I honestly don't know why it is the case and I was too lazy to dig deeper. If I think positively, it can even be a feature to avoid accidental tap on C-D ... OK I am just making up excuses ...

**Comment by oefe** [comment]
Well, at first I also thought that this fixes it, but after further playing with it, it happened again:

```
[stash-dev]$ test_raw.py 
first: a
first = a
second: b
second = b
third: c
third = c
[stash-dev]$ test_raw.py
first: 1
first = 1
second: stash: successfully terminated thread <Thread(_shruntime_thread, stopped daemon 241876992)>
[stash-dev]$ test_raw.py
first: q
first = q
second: w
second = w
third: e
third = e
[stash-dev]$ test_raw.py
first: y
second = y
third: stash: successfully terminated thread <Thread(_shruntime_thread, stopped daemon 224305152)>
[stash-dev]$ test_raw.py
first: yy
third = yy
[stash-dev]$ test_raw.py
first: qq
first = qq
second: ww
first = ww
second: ee
second = ee
third: rr
third = rr
[stash-dev]$ 
```

**Comment by oefe** [comment]
Works fine now, and getting a `ShKeyboardInterrupt` is much nicer than the scary "thread terminated" message, too!

Btw, why a custom exception? Wouldn't it better to raise a standard `KeyboardInterrupt`, so that scripts can handle it in the same way as on other platforms?

(Note to self: after a `git pull`, exit and restart `stash` before testing...)

**Comment by ywangd** [comment]
@oefe Pythonista seems to have some special handling for the `KeyboardInterrupt` exception. I tried with it first, but Pythonista would just step in to catch the exception and wouldn't allow stash to handle it even I have `try` block for it. Once Pythonista caught the exception, it left StaSh in an unusable state (it seems to me that Pythonista wipes `globals()` after catching the exception). So I have to use a customized exception. 

You are right that if the running script wants to catch the interrupt, it has to include specific code for StaSh, something like `if e.__class__.__name__ == 'ShKeyboardInterrupt': ...`. Fortunately, this special piece of code does NOT prevent it from running on other platforms.
