### ISSUE TITLE
Colors?

### ISSUE THREAD

**Issue by Vik2015** [ywangd/stash#119]
Is it possible to have different colors in StaSh (for different parts of text ofc)? Or this feature is not supported?

**Comment by dgelessus** [comment]
`ui.TextField`s can only have a single formatting for the entire text, so this is not easily possible. It would perhaps be possible to overlay colored `ui.Label`s over parts of the text to color them without affecting the text field below. That would be complicated to do though, and it would make scrolling impossible and probably affect cursor positioning and text selection in colored parts.

**Comment by Vik2015** [comment]
@dgelessus oh okay. I am not sure tho but I think Ole is going to add ctypes module in the next Pythonista. Maybe that'd enable to use some sort of styled text control or something :)

**Comment by jsbain** [comment]
I looked at the apple API for this, and it didn't look promising, since it requires callbacks, a feature unsupported in ctypes.

**Comment by ywangd** [comment]
A minor clarification, the text area is a `ui.TextView` not `TextField`. But still changing the font format affects all texts including even the existing texts.

**Comment by ywangd** [comment]
@jsbain With the new objc_util in 1.6 beta, is it possible to color the texts in `TextView`?

**Comment by jsbain** [comment]
yes.  it is tricky though, i have only been able to set the current style(i.e what you are about to type), and not retroactively style the whole thing, but that should be possible with enough experimentation.

**Comment by ywangd** [comment]
@jsbain It would be quite useful even only coloring for the current style. Would it be possible for you to provide an example on how it is done?

**Comment by jsbain** [comment]
see [here](https://github.com/jsbain/objc_hacks/blob/master/attrib_textview_typing.py).  actually, that is for fonts, let me look up color syntax

**Comment by jsbain** [comment]
ok, [here](https://github.com/jsbain/objc_hacks/blob/master/attribtext2.py) is an example that styles a textview that already has text in it.... if you replace range in sections, rather than replacing entire buffer, the formatting also stays intact...   i also updated the original to show dynamic colors

**Comment by ywangd** [comment]
Amazing! Thanks a lot for the code!!

**Comment by ywangd** [comment]
Attributed texts (including colors) are now possible with [beta16](https://github.com/ywangd/stash/tree/beta16) branch (requires Pythonista 1.6 beta). 

Thanks @jsbain for getting me started by providing the sample code!
