### ISSUE TITLE
certain globals survive different script executions

### ISSUE THREAD

**Issue by GeorgViehoever** [ywangd/stash#125]
if I run a python script from the stash console, certain globals survive across executions of the script. For instance, if a script appends to sys.path, a second execution of the script with extend sys.path again, making it longer and longer. I have seen this in my `wol.py` script.

I guess this is caused by the fact that in essence we are running in the same interpreter instance again and again. Still, I find it less than desirable that a process can essentially invalidate the environment for any other script.

Would it be possible do work around this, for instance by giving each script its own set of globals?

Georg

**Comment by dgelessus** [comment]
Not really. Even if you `exec` some code with empty globals, all module namespaces are shared. This includes `__builtin__`, where Python's built-in objects live, and `sys`, which holds some interpreter configuration like `sys.path` and `sys.modules`. There is no way to make code run in a completely separate clean Python environment within the same interpreter, at least not without `ctypes` magic. On a real computer you'd use subprocesses for that kind of thing, but that's not an option in the case of Pythonista.

**Comment by ywangd** [comment]
It is a bug that the `sys.path` grows every time the script runs. I'll make sure it is fixed soon and also add `lib` to default `sys.path` so scripts do not have to manipulate them.

Though it can be fixed for `sys.path` (by specifically save and restore it), @dgelessus is right that there is no general way to prevent scripts from making persistent environment changes. For an example, a script can decide to attach a new property to `sys`. It is impossible to catch and clear them all.

**Comment by ywangd** [comment]
`sys.path` is now fixed in `e59d6c76d3002cddcb08f2a2da680ec5c63d09ff`

**Comment by GeorgViehoever** [comment]
@dgelessus: After some reading I now understand that sys is shared by all threads, unless you create a new interpreter within the same process using the  Py_NewInterpreter(). I think this is not possible via ctypes, because this would basically need an interpreter thread to manipulate another interpreter thread while itself is running. 
I opened a feature request @omz for adding support for this.. https://forum.omz-software.com/topic/2109/wishlist-api-gui-for-new-interpreter
