### ISSUE TITLE
lib path no longer on path?

### ISSUE THREAD

**Issue by jsbain** [ywangd/stash#127]
In the beta, and latest master, git branch, merge, etc, which used import git.branch, etc, no longer function.   did we used to place stash/lib into sys.path?  

If we are moving away from that, perhaps we can add `_init__.py` to the lib folder, so that we can use from lib.git.branch.

**Comment by jsbain** [comment]
never mind.., apparantly i had gotten things in a funny configuration

**Comment by ywangd** [comment]
The `$STASH_ROOT/lib` was not part of `sys.path`. Your `git` code manually adds it at [line 44](https://github.com/ywangd/stash/blob/master/bin/git.py#L44).

However, this is now changed in the **dev** branch with commit e59d6c76d3002cddcb08f2a2da680ec5c63d09ff

The default `PYTHONPATH` is set to `$STASH_ROOT/lib`. So any scripts run within StaSh now have the lib path in `sys.path`. The advantage of using an environment variable is that it only affects scripts invoked from within the shell, i.e. it won't affect the interactive prompt.
