### ISSUE TITLE
Rationalise the exception handling

### ISSUE THREAD

**Issue by ywangd** [ywangd/stash#135]
Currently exceptions of running commands are handled in multiple places. These should be rationalised to clear their roles and potentially centralise the logic.

**Comment by jsbain** [comment]
In he latest beta things like StopIteration get incorrectly caught at the upper level.  For instance git branch uses some iterators, which break in te latest beta16 branch

**Comment by ywangd** [comment]
It seems to work for me. These are my test steps:
* Make a `stash` directory and 'cd' to the directory
* Clone stash into the directory by `git clone ...`
* type `git branch`

It correctly listed all the branches with master being the current one.
I also tried `git branch -av` and worked fine.

Did you get the issue in stash repo? Could you please advise on how I can reproduce it? What was the exact error message?
Thanks!

**Comment by jsbain** [comment]
whoops, i was not in a repo!  I will have to fix that....  
i thought StopIteration is what signals the end of a generator, so was surprised to see that trickle up as a top level exception.

**Comment by ywangd** [comment]
I noticed this error before even with version 0.4.x. It is caused by [this line](https://github.com/ywangd/stash/blob/beta16/lib/git/gitutils.py#L13) in `gitutils.py` (method `next` gets called on an exhausted `os.walk`). 

@oefe fixed a similar issue #116 that generates the same `StopIteration` error when running `git status`.

**Comment by ywangd** [comment]
Exception handle is reviewed and most of them are actually necessary. Comments added to clarify their purposes.
