### ISSUE TITLE
Issues getting ssh to work with pyte

### ISSUE THREAD

**Issue by dmkanter** [ywangd/stash#141]
When I try to ssh to a server, it seems to think pyte is missing and it attempts to install and then that fails. 

[~/Documents]$ ssh user@server.com
pyte module not found.
StaSh ssh installing pyte...
Opening: https://codeload.github.com/selectel/pyte/zip/master
Save as: /private/var/mobile/Containers/Shared/AppGroup/E8976D95-898E-44EF-A708-2161747BCF7C/Documents/site-packages/pyte.zip  
      8192
     16384
     24576
     32768
     40960
     49152
     52161
mv: Error: Destination path '/private/var/mobile/Containers/Shared/AppGroup/E8976D95-898E-44EF-A708-2161747BCF7C/Documents/site-packages/pyte/pyte' already exists
done
stash: <type 'exceptions.ImportError'>: No module named wcwidth

[~/Documents]$

**Comment by ywangd** [comment]
There are currently a few issues with `ssh` and `scp`:
* The builtin `paramiko` module (1.13) is not compatible with OpenSSH 6.7+, e.g. it errors out when trying to connect my OS X 10.11 with message *paramiko incompatible ssh peer*. You need upgrade to 1.15+ to fix the bug.
* `pyte` 0.5+ adds dependency on `wcwitdh` package. So it is better to use 0.4.x.
* The terminal mode needs pretty much a revamp (#133)

I haven't really got time to work on any of above issues. I'll keep you updated.

**Comment by dmkanter** [comment]
All your suggestions worked. I was able to ssh to one of my servers. Thanks!

**Comment by jsbain** [comment]
David, can you describe the steps you took?  Someone on the forums was looking for detailed instructions

**Comment by dmkanter** [comment]
It was pretty simple. 

Pip install paramiko
Pip install wcwidth
Ssh user@example.com -p password
