### ISSUE TITLE
Why is there a fullname param in which?

### ISSUE THREAD

**Issue by cclauss** [ywangd/stash#147]
`fullname` seems to be ignored in `bin/which.py`.  What is that param supposed to do?

**Comment by ywangd** [comment]
By default `which` print the abbreviated path for the given command, e.g. `~/Documents/bin/command.py`. 

If `fullname` is set to `True`, the path will be a fully expanded form, i.e. something like `/private/var/mobile/Containers/Shared/AppGroup/XSDFS-BSDSF-SDSFS/Documents/bin/command.py`.

You can see the difference by running `which version` and `which -f version`.
