### ISSUE TITLE
Should 'version' also print the Pythonista and/or iOS version?

### ISSUE THREAD

**Issue by cclauss** [ywangd/stash#152]
https://github.com/cclauss/Ten-lines-or-less/blob/master/pythonista_version.py

**Comment by ywangd** [comment]
Yes! I think it would be a great addition to add both Pythonista and iOS version info. I'll add them later. Thanks!

**Comment by ywangd** [comment]
The feature is now added with commit bf0c8f31096e0e6da207b2d9b50df6475062b539
