### ISSUE TITLE
os.path.isdir should ALWAYS be truthy

### ISSUE THREAD

**Issue by cclauss** [ywangd/stash#154]
line 25 of bin/cd.py asks if os.path.isdir is truthy.  I think this was meant to be a function __call__ instead of just asking if the function is truthy.

**Comment by ywangd** [comment]
You are right. This is a bug. It should have been a function call for the dir in question.

**Comment by ywangd** [comment]
This is now fixed with commit a6bf8d17e1b6cda8e758f5c55eb71c3994146eb1
