### ISSUE TITLE
Use ~/.ssh as default for ssh_keygen, etc

### ISSUE THREAD

**Issue by jsbain** [ywangd/stash#156]
In recent versions, the ~ folder is writable.  Thus ~/.ssh is now accessible.  This lets us store ssh keys in the proper location, i.e where paramiko searches for system hosts and keys, so allows third party libraries to work.
I believe ssh-keygen should be updated to use ~/.ssh rather than stash/.ssh.

**Comment by ywangd** [comment]
Fixed in commit 79e4725a92af2e4ec3dd76d136e43773ab116f9b

ssh-keygen now saves the keys in `~/.ssh` as well as `$STASH_ROOT/.ssh` for backwards compatibility.

You can update with `selfupdate dev`
