### ISSUE TITLE
stash is mirroring os.curpath

### ISSUE THREAD

**Issue by jsbain** [ywangd/stash#161]
Previous behavior was that stash was independant of console or python environment.  Now, fo example running a script, causes stash path to change, which could cause some surprising results.

Not sure if this was intentional-- i could see some use cases, as cd is simpler to write than os.chdir.  perhaps a separate command (lcd? similar to ftp) or maybe a flag for cd?

**Comment by ywangd** [comment]
This is a bug. I noticed that the directory changes after running `pip`. I have since fixed it with 9ff1464bbb8e1911a0f3fb37e349a93102d9dafa 
It is available in the `dev` and `py3` branch. You can update to latest `dev` with `selfupdate -f dev`.

**Comment by ywangd** [comment]
By the way, the callable interface does accept a `persistent_level` keyword which decides how the changes in sub-shell affects its parent shell. By default, `_stash('cd some_dir')` should not change current/parent shell's directory. But if you call it like `_stash('cd some_dir', persistent_level=1)`, then directory change will be available in parent shell as well.
