### ISSUE TITLE
Memoryleak in Pythonista 3 and 2.1

### ISSUE THREAD

**Issue by bennr01** [ywangd/stash#180]
There seems to be some sort of memory leak in StaSh.
When entering a command or an empty line in the StaSh commandline, the amount of objects in `gc.garbage` increases (write `gci status` to the StaSh prompt to get the amount of garbage).
When setting the debuglevel of the garbagecollector to `DEBUG_LEAK`, it will print a huge list of uncollectable objects, most of them appear to be some UI-Buttons on objc-level (write `gci debug 62` to the StaSh-prompt to set debug to `DEBUG_LEAK`).
I have tested this with Pythonista3 (2.7.5), Pythonista 2.1 and 2.
Pythonista 2.0 does not seem to have any issues.
Pythonista3 and Pythonista 2.1 have memoryleaks when running StaSh.
Running normal scripts outside StaSh does not result in any memoryleaks.
The size of the garbage exeeds 1MB pretty fast.
I have tested this with the ywangd/dev branch.

**Comment by ywangd** [comment]
Thanks for the issue report. I'll look into it when I have more time. Unfortunately I am very occupied with other things. So this will take a while.

**Comment by Seanld** [comment]
@ywangd are you working on a new release or something? You haven't made a commit in a while.

**Comment by ywangd** [comment]
I am not working on new releases. Simply do not have any time for it at this stage ...

**Comment by steljas** [comment]
@bennr01 Is this behavior different from default Pythonista behavior?  Without running stash and just using the Pythonista console, I'm seeing a consistent growth of garbage objects that don't seem to be "collectable".  The following is console output from Pythonista 3.1 (301016), on iOS 11.2.1 (64-bit iPad6,3), with a fresh launch of Pythonista:

```
>>> import gc
>>> tracked = gc.get_objects()
>>> print len(tracked)
4248
>>> tracked = gc.get_objects()
>>> print len(tracked)
4253
>>> tracked = gc.get_objects()
>>> print len(tracked)
4258
>>> gc.collect()
0
>>> tracked = gc.get_objects()
>>> print len(tracked)
4264
```

**Comment by bennr01** [comment]
@steljas sorry for the delayed response. It appears like this was a bug in the pythonista UI module related with keyboard inputs (the increase in garbage was proportional to the numbers of keys pressed since the last check) and was fixed a few weeks later in a pythonista update.
Thanks for reminding me to close this issue.
