### ISSUE TITLE
No module named stash from running launch_stash.py

### ISSUE THREAD

**Issue by groner** [ywangd/stash#184]
I am a new Pythonista 3 user.  My ipad has iOS 9.3.2.

I ran the snippet to download and evaluate `bit.ly/get-stash`, which appears to have successfully populated `site-packages/stash/` and `launch_stash.py`.  When I try to run `launch_stash.py`, I get an import error on line 28 (`from stash import stash`).

I am able to locate the stash package/modules using the following snippet.
```python
import glob
import sys
for pth in sys.path:
  for f in glob.glob('{}/stash/__init__.py'.format(pth)): print f
  for f in glob.glob('{}/stash/stash.py'.format(pth)): print f
```

I have also checked that there are no entries in `sys.modules` that begin with `'stash'`.

I don't understand why this isn't working.  Got any ideas?

**Comment by groner** [comment]
I restarted Pythonista and now it works.

**Comment by ywangd** [comment]
I'll add a notice in the installation script to ask for restarting Pythonista to avoid confusion. Thanks!

**Comment by siulman** [comment]
Hello, I have the same issue than @groner here. I am using Ipad pro 10.5 with pythonista. I tryed to restart pythonista 3 and even the ipad but it didn’t change anything. I can’t launch “launch_stach.py”

Could you please help?

**Comment by PeterGriffinJin** [comment]
I have the same problem too! What should I do ?

**Comment by azuryl** [comment]
> I restarted Pythonista and now it works.

how to restart  Pythonista
