### ISSUE TITLE
Trying to use git clone, downloading dulwich fails.

### ISSUE THREAD

**Issue by Tkizzy** [ywangd/stash#192]
When trying to clone a git repo, I get the following...

```
Need to download dulwich.  OK to download [y/n]?y
Opening: https://github.com/jsbain/dulwich/archive/ForStaSH_0.12.2.zip
Save as: /private/var/mobile/Containers/Data/Application/30242052-8625-4665-9AB7-67AE63969A2F/tmp/dulwich.zip  
    400490 
/private/var/mobile/Containers/Shared/AppGroup/579D678C-22E6-4C16-A07A-D661B02C66E1/Pythonista3/Documents/site-packages/stash/lib/dulwich.old: does not exist
mv: /private/var/mobile/Containers/Shared/AppGroup/579D678C-22E6-4C16-A07A-D661B02C66E1/Pythonista3/Documents/site-packages/stash/lib/dulwich: no such file or directory
/private/var/mobile/Containers/Shared/AppGroup/579D678C-22E6-4C16-A07A-D661B02C66E1/Pythonista3/Documents/site-packages/stash/lib/dulwich.old: does not exist
Opening: https://github.com/jsbain/gittle/archive/master.zip
Save as: /private/var/mobile/Containers/Data/Application/30242052-8625-4665-9AB7-67AE63969A2F/tmp/gittle.zip  
     28334 
Opening: https://github.com/FriendCode/funky/archive/master.zip
Save as: /private/var/mobile/Containers/Data/Application/30242052-8625-4665-9AB7-67AE63969A2F/tmp/funky.zip  
      8474 
stash: <class 'ImportError'>: No module named 'urlparse'

[~/Documents]$ 
```

Worth mentioning I did do self update
```
StaSh v0.7.0a10
Tip: You can omit .py when typing command name, e.g. pwd is the same as pwd.py
[~/Documents]$ selfupdate
Running selfupdate ...
Branch: master
Checking for new version ...
Already at latest version
```

**Comment by ywangd** [comment]
The version you are using is the previous py3 branch. It is not completed
and since discarded when omz made Pythonista support both 2 and 3.

You can get the latest stable release via `selfupdate -f` and restart
Pythonista. The current version should be 0.6.11

On Tuesday, 12 July 2016, Tizzy <notifications@github.com> wrote:

> When trying to clone a git repo, I get the following...
>
> Need to download dulwich.  OK to download [y/n]?y
> Opening: https://github.com/jsbain/dulwich/archive/ForStaSH_0.12.2.zip
> Save as: /private/var/mobile/Containers/Data/Application/30242052-8625-4665-9AB7-67AE63969A2F/tmp/dulwich.zip
>     400490
> /private/var/mobile/Containers/Shared/AppGroup/579D678C-22E6-4C16-A07A-D661B02C66E1/Pythonista3/Documents/site-packages/stash/lib/dulwich.old: does not exist
> mv: /private/var/mobile/Containers/Shared/AppGroup/579D678C-22E6-4C16-A07A-D661B02C66E1/Pythonista3/Documents/site-packages/stash/lib/dulwich: no such file or directory
> /private/var/mobile/Containers/Shared/AppGroup/579D678C-22E6-4C16-A07A-D661B02C66E1/Pythonista3/Documents/site-packages/stash/lib/dulwich.old: does not exist
> Opening: https://github.com/jsbain/gittle/archive/master.zip
> Save as: /private/var/mobile/Containers/Data/Application/30242052-8625-4665-9AB7-67AE63969A2F/tmp/gittle.zip
>      28334
> Opening: https://github.com/FriendCode/funky/archive/master.zip
> Save as: /private/var/mobile/Containers/Data/Application/30242052-8625-4665-9AB7-67AE63969A2F/tmp/funky.zip
>       8474
> stash: <class 'ImportError'>: No module named 'urlparse'
>
> [~/Documents]$
>
> Worth mentioning I did do self update
>
> StaSh v0.7.0a10
> Tip: You can omit .py when typing command name, e.g. pwd is the same as pwd.py
> [~/Documents]$ selfupdate
> Running selfupdate ...
> Branch: master
> Checking for new version ...
> Already at latest version
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ywangd/stash/issues/192>, or mute the thread
> <https://github.com/notifications/unsubscribe/ACPFdMppYFM2AR21YMGIz3U5V0ZnVkkZks5qUsH0gaJpZM4JJ27v>
> .
>


-- 
----------------------------------------------------------------------
                      Life is elsewhere

**Comment by Tkizzy** [comment]
The above is using the latest pythonista 3 beta. 

Trying to do the same in Pythonista 2 with StaSh .6.11 yields the following error:
```
stash: <type 'exceptions.OSError'>: [Errno 17] File exists: './.git'
```

**Comment by ywangd** [comment]
You need remove the .git folder which is a debris left by previous failed
git call. Run `rm -rf .git` first and run your git clone afterwards. Thanks!

On Tuesday, 12 July 2016, Tizzy <notifications@github.com> wrote:

> The above is using the latest pythonista 3 beta.
>
> Trying to do the same in Pythonista 2 with StaSh .6.11 yields the
> following error:
>
> stash: <type 'exceptions.OSError'>: [Errno 17] File exists: './.git'
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/ywangd/stash/issues/192#issuecomment-231884835>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ACPFdBnXKBkbHQ2B-AHtGZoo7Q9si6W7ks5qUsNkgaJpZM4JJ27v>
> .
>


-- 
----------------------------------------------------------------------
                      Life is elsewhere

**Comment by Tkizzy** [comment]
Thanks @ywangd for your incredibly prompt replies! 8^)

**Comment by ywangd** [comment]
You are welcome :)

**Comment by Tkizzy** [comment]
By the way when I run the stash tests, here's what I get.

```

EEEEE
======================================================================
ERROR: tests.test_completer (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_completer
Traceback (most recent call last):
  File "/var/containers/Bundle/Application/537C5EDE-81F5-4C3E-9B60-31E2AC62368D/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/unittest/loader.py", line 429, in _find_test_path
    module = self._get_module_from_name(name)
  File "/var/containers/Bundle/Application/537C5EDE-81F5-4C3E-9B60-31E2AC62368D/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/unittest/loader.py", line 370, in _get_module_from_name
    __import__(name)
  File "/private/var/mobile/Containers/Shared/AppGroup/579D678C-22E6-4C16-A07A-D661B02C66E1/Pythonista3/Documents/site-packages/stash/system/tests/test_completer.py", line 4, in <module>
    import stash
  File "/private/var/mobile/Containers/Shared/AppGroup/579D678C-22E6-4C16-A07A-D661B02C66E1/Pythonista3/Documents/site-packages/stash/stash.py", line 12, in <module>
    from ConfigParser import ConfigParser
ImportError: No module named 'ConfigParser'


======================================================================
ERROR: tests.test_expander (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_expander
Traceback (most recent call last):
  File "/var/containers/Bundle/Application/537C5EDE-81F5-4C3E-9B60-31E2AC62368D/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/unittest/loader.py", line 429, in _find_test_path
    module = self._get_module_from_name(name)
  File "/var/containers/Bundle/Application/537C5EDE-81F5-4C3E-9B60-31E2AC62368D/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/unittest/loader.py", line 370, in _get_module_from_name
    __import__(name)
  File "/private/var/mobile/Containers/Shared/AppGroup/579D678C-22E6-4C16-A07A-D661B02C66E1/Pythonista3/Documents/site-packages/stash/system/tests/test_expander.py", line 5, in <module>
    import stash
  File "/private/var/mobile/Containers/Shared/AppGroup/579D678C-22E6-4C16-A07A-D661B02C66E1/Pythonista3/Documents/site-packages/stash/stash.py", line 12, in <module>
    from ConfigParser import ConfigParser
ImportError: No module named 'ConfigParser'


======================================================================
ERROR: tests.test_runtime (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_runtime
Traceback (most recent call last):
  File "/var/containers/Bundle/Application/537C5EDE-81F5-4C3E-9B60-31E2AC62368D/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/unittest/loader.py", line 429, in _find_test_path
    module = self._get_module_from_name(name)
  File "/var/containers/Bundle/Application/537C5EDE-81F5-4C3E-9B60-31E2AC62368D/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/unittest/loader.py", line 370, in _get_module_from_name
    __import__(name)
  File "/private/var/mobile/Containers/Shared/AppGroup/579D678C-22E6-4C16-A07A-D661B02C66E1/Pythonista3/Documents/site-packages/stash/system/tests/test_runtime.py", line 5, in <module>
    import stash
  File "/private/var/mobile/Containers/Shared/AppGroup/579D678C-22E6-4C16-A07A-D661B02C66E1/Pythonista3/Documents/site-packages/stash/stash.py", line 12, in <module>
    from ConfigParser import ConfigParser
ImportError: No module named 'ConfigParser'


======================================================================
ERROR: tests.test_termemu (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_termemu
Traceback (most recent call last):
  File "/var/containers/Bundle/Application/537C5EDE-81F5-4C3E-9B60-31E2AC62368D/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/unittest/loader.py", line 429, in _find_test_path
    module = self._get_module_from_name(name)
  File "/var/containers/Bundle/Application/537C5EDE-81F5-4C3E-9B60-31E2AC62368D/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/unittest/loader.py", line 370, in _get_module_from_name
    __import__(name)
  File "/private/var/mobile/Containers/Shared/AppGroup/579D678C-22E6-4C16-A07A-D661B02C66E1/Pythonista3/Documents/site-packages/stash/system/tests/test_termemu.py", line 4, in <module>
    import stash
  File "/private/var/mobile/Containers/Shared/AppGroup/579D678C-22E6-4C16-A07A-D661B02C66E1/Pythonista3/Documents/site-packages/stash/stash.py", line 12, in <module>
    from ConfigParser import ConfigParser
ImportError: No module named 'ConfigParser'


======================================================================
ERROR: tests.test_threads (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_threads
Traceback (most recent call last):
  File "/var/containers/Bundle/Application/537C5EDE-81F5-4C3E-9B60-31E2AC62368D/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/unittest/loader.py", line 429, in _find_test_path
    module = self._get_module_from_name(name)
  File "/var/containers/Bundle/Application/537C5EDE-81F5-4C3E-9B60-31E2AC62368D/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/unittest/loader.py", line 370, in _get_module_from_name
    __import__(name)
  File "/private/var/mobile/Containers/Shared/AppGroup/579D678C-22E6-4C16-A07A-D661B02C66E1/Pythonista3/Documents/site-packages/stash/system/tests/test_threads.py", line 5, in <module>
    from StringIO import StringIO
ImportError: No module named 'StringIO'


----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (errors=5)


```

**Comment by ywangd** [comment]
This is because you ran the tests with Python 3 interpreter and stash is
not Python 3 ready yet. The `launch_stash.py` script has a python2 shebang
to tell Pythonista to use Python 2, while the runtests does not contain any
shebang lines.

PS: I have Travis CI configured to run the tests on every commit. So rest
assured that they are always up to date.

On Tue, Jul 12, 2016 at 9:26 AM, Tizzy <notifications@github.com> wrote:

> By the way when I run the stash tests, here's what I get.
>
>
> EEEEE
> ======================================================================
> ERROR: tests.test_completer (unittest.loader._FailedTest)
> ----------------------------------------------------------------------
> ImportError: Failed to import test module: tests.test_completer
> Traceback (most recent call last):
>   File "/var/containers/Bundle/Application/537C5EDE-81F5-4C3E-9B60-31E2AC62368D/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/unittest/loader.py", line 429, in _find_test_path
>     module = self._get_module_from_name(name)
>   File "/var/containers/Bundle/Application/537C5EDE-81F5-4C3E-9B60-31E2AC62368D/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/unittest/loader.py", line 370, in _get_module_from_name
>     __import__(name)
>   File "/private/var/mobile/Containers/Shared/AppGroup/579D678C-22E6-4C16-A07A-D661B02C66E1/Pythonista3/Documents/site-packages/stash/system/tests/test_completer.py", line 4, in <module>
>     import stash
>   File "/private/var/mobile/Containers/Shared/AppGroup/579D678C-22E6-4C16-A07A-D661B02C66E1/Pythonista3/Documents/site-packages/stash/stash.py", line 12, in <module>
>     from ConfigParser import ConfigParser
> ImportError: No module named 'ConfigParser'
>
>
> ======================================================================
> ERROR: tests.test_expander (unittest.loader._FailedTest)
> ----------------------------------------------------------------------
> ImportError: Failed to import test module: tests.test_expander
> Traceback (most recent call last):
>   File "/var/containers/Bundle/Application/537C5EDE-81F5-4C3E-9B60-31E2AC62368D/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/unittest/loader.py", line 429, in _find_test_path
>     module = self._get_module_from_name(name)
>   File "/var/containers/Bundle/Application/537C5EDE-81F5-4C3E-9B60-31E2AC62368D/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/unittest/loader.py", line 370, in _get_module_from_name
>     __import__(name)
>   File "/private/var/mobile/Containers/Shared/AppGroup/579D678C-22E6-4C16-A07A-D661B02C66E1/Pythonista3/Documents/site-packages/stash/system/tests/test_expander.py", line 5, in <module>
>     import stash
>   File "/private/var/mobile/Containers/Shared/AppGroup/579D678C-22E6-4C16-A07A-D661B02C66E1/Pythonista3/Documents/site-packages/stash/stash.py", line 12, in <module>
>     from ConfigParser import ConfigParser
> ImportError: No module named 'ConfigParser'
>
>
> ======================================================================
> ERROR: tests.test_runtime (unittest.loader._FailedTest)
> ----------------------------------------------------------------------
> ImportError: Failed to import test module: tests.test_runtime
> Traceback (most recent call last):
>   File "/var/containers/Bundle/Application/537C5EDE-81F5-4C3E-9B60-31E2AC62368D/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/unittest/loader.py", line 429, in _find_test_path
>     module = self._get_module_from_name(name)
>   File "/var/containers/Bundle/Application/537C5EDE-81F5-4C3E-9B60-31E2AC62368D/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/unittest/loader.py", line 370, in _get_module_from_name
>     __import__(name)
>   File "/private/var/mobile/Containers/Shared/AppGroup/579D678C-22E6-4C16-A07A-D661B02C66E1/Pythonista3/Documents/site-packages/stash/system/tests/test_runtime.py", line 5, in <module>
>     import stash
>   File "/private/var/mobile/Containers/Shared/AppGroup/579D678C-22E6-4C16-A07A-D661B02C66E1/Pythonista3/Documents/site-packages/stash/stash.py", line 12, in <module>
>     from ConfigParser import ConfigParser
> ImportError: No module named 'ConfigParser'
>
>
> ======================================================================
> ERROR: tests.test_termemu (unittest.loader._FailedTest)
> ----------------------------------------------------------------------
> ImportError: Failed to import test module: tests.test_termemu
> Traceback (most recent call last):
>   File "/var/containers/Bundle/Application/537C5EDE-81F5-4C3E-9B60-31E2AC62368D/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/unittest/loader.py", line 429, in _find_test_path
>     module = self._get_module_from_name(name)
>   File "/var/containers/Bundle/Application/537C5EDE-81F5-4C3E-9B60-31E2AC62368D/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/unittest/loader.py", line 370, in _get_module_from_name
>     __import__(name)
>   File "/private/var/mobile/Containers/Shared/AppGroup/579D678C-22E6-4C16-A07A-D661B02C66E1/Pythonista3/Documents/site-packages/stash/system/tests/test_termemu.py", line 4, in <module>
>     import stash
>   File "/private/var/mobile/Containers/Shared/AppGroup/579D678C-22E6-4C16-A07A-D661B02C66E1/Pythonista3/Documents/site-packages/stash/stash.py", line 12, in <module>
>     from ConfigParser import ConfigParser
> ImportError: No module named 'ConfigParser'
>
>
> ======================================================================
> ERROR: tests.test_threads (unittest.loader._FailedTest)
> ----------------------------------------------------------------------
> ImportError: Failed to import test module: tests.test_threads
> Traceback (most recent call last):
>   File "/var/containers/Bundle/Application/537C5EDE-81F5-4C3E-9B60-31E2AC62368D/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/unittest/loader.py", line 429, in _find_test_path
>     module = self._get_module_from_name(name)
>   File "/var/containers/Bundle/Application/537C5EDE-81F5-4C3E-9B60-31E2AC62368D/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/unittest/loader.py", line 370, in _get_module_from_name
>     __import__(name)
>   File "/private/var/mobile/Containers/Shared/AppGroup/579D678C-22E6-4C16-A07A-D661B02C66E1/Pythonista3/Documents/site-packages/stash/system/tests/test_threads.py", line 5, in <module>
>     from StringIO import StringIO
> ImportError: No module named 'StringIO'
>
>
> ----------------------------------------------------------------------
> Ran 5 tests in 0.002s
>
> FAILED (errors=5)
>
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ywangd/stash/issues/192#issuecomment-231895305>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ACPFdIasCDBXAUa7QXhvjes2AkadOUb5ks5qUtFBgaJpZM4JJ27v>
> .
>



-- 
----------------------------------------------------------------------
                      Life is elsewhere

**Comment by Tkizzy** [comment]
I see @ywangd. Sounds like you are on top of it. Forgive me if this is an inappropriate place to ask this next question.

I'm trying to follow along w/the stash github tutorial, but there is no mention of how to authenticate w/a github account to be able to push to it... How does one do so?

**Comment by ywangd** [comment]
What I do is as follows:
* Run `ssh-keygen` to create a pair of private and public keys  (they are stored under `~/.ssh/`)
* Login on github using a webbrowser and add a new SSH key (in settings)
* Click `new SSH key`, give it a title and copy the contents of `~/.ssh/id_rsa.pub` into the `key` text input. Then click "Add SSH Key" to save

Now you should be able to use ssh for GitHub without having to type username and password. Note that when cloning a repo, you'll need to use the SSH URL, .e.g. something like `ssh://git@github.com/owner/repo.git`

**Comment by Tkizzy** [comment]
Thanks, ywangd , I followed the above instructions to the key, but no cigar :(. I was trying to create a repo as per https://github.com/ywangd/stash_git_tutorial/blob/master/stash_git_tutorial.md

```
testGitProject1]$ gh create -aid -s "test stash git proj" stash_git_test_thing1
stash: <type 'exceptions.KeyError'>: 'stash.git.github.com'

```

**Comment by jsbain** [comment]
gh uses a keychain key, not ssh.  

Either so a pushto an existing repo first, or use
keychain.set_password('stash.git.github.com', user, pw)

**Comment by Tkizzy** [comment]
Ok, thank you @jsbain that did the trick!

**Comment by Tkizzy** [comment]
I should probably close this issue, Huh? 

But rather than opening another issue, I'm going to put this here because I suspect it might be my incompetence and I don't want to muddy up StaSh's issues.

Issue: 
```
stash: <type 'exceptions.TypeError'>: object of type 'NoneType' has no len()
```

I'm getting the above error when I try to do a merge, after having successfully done a fetch. 

I'll back up.

I used `gh create ....` as per your tutorial, @ywangd . I then did some commits and pushes, all successfully. I then cloned in working copy, modified the readme, committed and pushed. It appears correctly on github. Then, I did a fetch in StaSh. A merge directly after causes the above mentioned error. Am I doing something wrong?

**Comment by Tkizzy** [comment]
Correction: I guess the tutorial was made by you, @jsbain, I believe.

**Comment by Tkizzy** [comment]
Also, I'm getting a ```stash: <type 'exceptions.KeyError'>: 'HEAD'``` when trying to do git status after having done an add,commit,push, and then modified the file some more in Pythonista....

**Comment by Tkizzy** [comment]
Also, stash seems to sometimes randomly change the folder I'm cd'd into....
