### ISSUE TITLE
Python 3: Package structure and relative imports

### ISSUE THREAD

**Issue by dgelessus** [ywangd/stash#193]
I've been looking at Stash's package structure a bit (for the `universal` branch). I noticed that many modules use implicit relative imports (e. g. `stash.py` imports `system.shcommon`, which actually imports `stash.system.shcommon`) which do not work under Python 3. This is not a big issue, most of these can be replaced with real relative imports (e. g. `from .system import shcommon`).

The second issue (not directly related to the first one) is that the repo root is the `stash` package folder, i. e. `site-package/stash` is the repo root. This means that you have to clone the repo into `site-packages/stash`, or some imports (for example in `launch_stash.py` will fail). So it's not possible to have two versions of Stash installed without changing the package name and adjusting imports.

A solution to this would be to move all Stash module files (like `stash.py` and `system`) into a `stash` subfolder, while leaving non-module files in the repo root (like `launch_stash.py`). This would make installing multiple versions or switching between branches much easier. The `launch_stash.py` would be in the same folder as the `stash` package, so when it imports `stash` it automatically uses the version next to it instead of the one from `site-packages`.

For normal users nothing would change - if there is no `stash` package in the same folder as `launch_stash.py`, it looks through the other module locations, including `site-packages`. `getstash.py` would only need some minor modifications to copy the `stash` folder into `site-packages` and not the entire repo.

**Comment by ywangd** [comment]
Yes the relative imports need to be fixed. Thanks.

However, having multiple stash installations is actually something I try to avoid. I agree it is useful for development purpose. But for most users, this possibility is more likely to cause confusions, e.g. one may wonder why `selfupdate` does not work as it is probably updating another version which is not the currently running one.

**Comment by dgelessus** [comment]
Yes, that's understandable, users shouldn't install multiple stash instances by accident. However I don't think this change would affect stash installations in `site-packages` - as long as we change `getstash.py` to understand the new structure, `selfupdate` would work the same as before for normal users.

The difference is that with the old structure, when you clone the repo *by hand* into a different folder, the `launch_stash.py` in the repo would still use the stash installation in `site-packages`, and not the one in the cloned repo. With the new structure, `launch_stash.py` would prefer importing stash from the current directory, and fall back to `site-packages` if there is no valid `stash` package next to the `launch_stash.py`.
