### ISSUE TITLE
new git problems 

### ISSUE THREAD

**Issue by sloanlance** [ywangd/stash#197]
Over the past two days, I've performed several successful git operations with git.py in StaSh. However, this morning, I've seen errors like this several times:

```
[requests]$ git status 
Opening: https://github.com/jsbain/gittle/archive/master.zip
Save as: /private/var/mobile/Containers/Data/Application/48248CF5-BD0F-4DAC-9CD2-3C8CC38561E8/tmp/gittle.zip (28334 bytes)
     28334  [100.00%]
mv: Error: Destination path '/private/var/mobile/Containers/Shared/AppGroup/A1D74EBC-2B9B-499A-A57A-FE13B13B34B6/Documents/site-packages/stash/lib/gittle/gittle' already exists
Opening: https://github.com/FriendCode/funky/archive/master.zip
Save as: /private/var/mobile/Containers/Data/Application/48248CF5-BD0F-4DAC-9CD2-3C8CC38561E8/tmp/funky.zip (8474 bytes)
      8474  [100.00%]
mv: Error: Destination path '/private/var/mobile/Containers/Shared/AppGroup/A1D74EBC-2B9B-499A-A57A-FE13B13B34B6/Documents/site-packages/stash/lib/funky/funky' already exists
stash: <type 'exceptions.ImportError'>: cannot import name utils

[requests]$ 
```

I've tried deleting packages funky and gittle, both together and individually, but it makes no difference. I'm not sure which program is having trouble or which util is to be imported. FWIW, I'm working in a clone of requests.

**Comment by ywangd** [comment]
I think `utils` is a submodule of `gittle` and you should be able to find it at `~/Documents/site-packages/stash/lib/gittle/utils`

It seems that stash could not locate these modules. So you may wanna check whether the modules are indeed installed completely at correct location. 
First, `echo $STASH_ROOT` see if you were running stash from the correct location. The output should be `~/Documents/site-packages/stash/`. 
Next, check whether the modules (dulwich, gittle, funcky) are correctly installed under `$STASH_ROOT/lib/`.
Third, run `echo $PYTHONPATH | grep stash` to check whether the search paths are correct. You should see the word `stash` in red colour in the output.

If everything looks fine and stash git still does not work, you should then try restart Pythonista, i.e. double press the home button and swipe up to remove Pythonista from the task list. At this point, the problem would likely be gone. But if not, please let me know.

**Comment by sloanlance** [comment]
I decided to take a chance and go for the "IT Crowd" approach first. I stopped and restarted Pythonista, now all works well. *slaps forehead*

Thanks!
