### ISSUE TITLE
Do packages like aiohttp require a pip3 instead of pip?

### ISSUE THREAD

**Issue by cclauss** [ywangd/stash#200]
On a Mac, if you do `brew install python python3 pypy pypy3` then you get four different pip binaries on your machine: `pip, pip3, pip_pypy, and pip_pypy3`.  This is exactly the same binary installed four times but each one installs packages into a different Python runtime.

The module [`aiohttp`](http://aiohttp.readthedocs.io/) is a pure Python module that does what the `requests` module does but on top of asyncio (thus Python 3 only).  It also does server side and WebSockets.  It is nothing short of awesome for doing concurrent web development.  If you try to use stash to install it, you get:

```
StaSh v0.6.13
[~/Documents]$ pip install aiohttp
Creating package file
Querying PyPI ... 
Downloading package ...
Opening: https://pypi.python.org/packages/55/9d/38fb3cb174f4723b50a3f0593e18a51418c9a73a7857fdcaee46b83ff1c4/aiohttp-0.22.5.tar.gz
Save as: /private/var/mobile/Containers/Data/Application/<deleted>/tmp/aiohttp-0.22.5.tar.gz (475312 bytes)
    475312  [100.00%]
Extracting archive file ...
Archive extracted.
Running setup file ...
RuntimeError('aiohttp requires Python 3.4.1+',)
Failed to run setup.py
Fall back to directory guessing ...
Package installed: aiohttp
```

The module is indeed on your machine but the RuntimeError happens because stash pip is Python 2, the script fails to run so the dependencies (multidict, chardet, errors?) are not loaded.  **Would it be possible to add a pip3 command to stash that would run under Python 3 to properly install Python 3-only packages like aiohttp, etc.?**

**Comment by mikaelho** [comment]
Is there a resolution to be expected or a workaround? Would have a need for aiohttp.

**Comment by feinstruktur** [comment]
I'm getting a similar issue when trying to install asyncpg, a pure python 3.5+ postgres driver.
