### ISSUE TITLE
Git add: "does not exist. skipping"

### ISSUE THREAD

**Issue by wizardofozzie** [ywangd/stash#206]
```
StaSh v0.6.16
Tip: Download files from an URL with wget
[~/Documents]$ cd ceid-fixer/
[ceid-fixer]$ git add *
ceid-fixer/__init__.py does not exist. skipping
ceid-fixer/ceidfixer.py does not exist. skipping
ceid-fixer/doc.kml does not exist. skipping
ceid-fixer/fkml.py does not exist. skipping
ceid-fixer/kmlclass.py does not exist. skipping
[ceid-fixer]$ cd ../a
../ab.zip  ../add_playground_page.py  ../aes.py  ../alphabear-solver/
[ceid-fixer]$ cd ../alphabear-solver/
[alphabear-solver]$ git add *
Adding README.md
Adding dictionary.txt
Adding hashdict.py
Adding lastsearch.txt
Adding map.json
Adding solver.py
[alphabear-solver]$ 
```

**Comment by jsbain** [comment]
My guess: you have ~/Documents/.git, and no ceid-fixer/.git.  
There is a bug in git where it does not let you add from a subfolder within a repo, which is what produces that message.  So I suspect you accidentally setup Documents as your repo.

Reclone, or move tye .git folder.

**Comment by wizardofozzie** [comment]
Ok, so the bug is that `git clone giturl` (no folder at the end) will default to `~/Documents`? Or is it if the cwd is Documents?

**Comment by jsbain** [comment]
git clone giturl clones to the cwd. 
 I suppose this is surprising and not what is usually intended.

**Comment by Seanld** [comment]
This is a weird issue...

Maybe when they were _previously_ added to your Git cache, they were stored for future adds, but aren't located in that directory anymore? I don't know why that would give you issues, but oh well.
