### ISSUE TITLE
Debugging of failing commands

### ISSUE THREAD

**Issue by jmgc** [ywangd/stash#208]
First of all I want to say that the work done in StaSh is impressive. I have worked a little, and most commands worked without flaws.

Then I have gone to scp and ssh and some Python errors appeared on the console, but the information did not provide the file and line of the error to try to find it, and if it was minor, correct it. How can I increase the verbosity of the errors?

**Comment by jsbain** [comment]
stashconf py_traceback 1 to print tracebacks
or
stashconf py_pdb 1 to automatically start the debugger

there are corresponding options in the  default config file (line 55 in stash.py) or in your own custom .stash_conf

**Comment by jmgc** [comment]
Perfect!

Thanks,

Jose M.
