### ISSUE TITLE
Problem starting Stash

### ISSUE THREAD

**Issue by allanbr1** [ywangd/stash#219]
Hi,

Just installed stash on Pythonista on my iPad (iOS 9) and it's working great.

But, can't seem to make it work on my iPhone (iOS 10). When I run launch_stash.py for the first time I get an error.

ImportError: cannot import name stash
Line 28: <module>

**Comment by dgelessus** [comment]
Silly question - did you remember to restart Pythonista after installing Stash? Otherwise an incorrectly cached version of the `stash` module can get loaded by accident and won't work correctly.

**Comment by joejenb** [comment]
Hi, 
I've got the same issue.

**Comment by Seanld** [comment]
Other than the answer @dgelessus gave, I can't imagine any other reason for this error except for running StaSh on Pythonista instead of Pythonista 3. I'm not sure if the code is optimized for the original Pythonista which uses Python 2 instead of 3.
