### ISSUE TITLE
pip doesn't work.

### ISSUE THREAD

**Issue by i0nsec** [ywangd/stash#241]
[~/Documents]$ pip install pyping
stash: <type 'exceptions.TypeError'>: __call__() takes exactly 2 arguments (1 given)

**Comment by bennr01** [comment]
Hi @i0nsec,
Have you checked [this thread on the forum](https://forum.omz-software.com/topic/3956/stash-problem)? It appears to be the same issue.

**Comment by i0nsec** [comment]
Perfect, it worked. Thanks.
