### ISSUE TITLE
 Cannot locate packages. Manual installation required.

### ISSUE THREAD

**Issue by Enjia** [ywangd/stash#243]
I want to pip the sklearn packages and this issue occured:
-------------------------------------------------------------
[~/Documents]$ pip install sklearn
Querying PyPI ... 
Downloading package ...
Opening: https://pypi.python.org/packages/1e/7a/dbb3be0ce9bd5c8b7e3d87328e79063f8b263b2b1bfa4774cb1147bfcd3f/sklearn-0.0.tar.gz
Save as: /private/var/mobile/Containers/Data/Application/2FDF8EB1-7BD8-4F6B-BF13-835FD5626CA9/tmp//sklearn-0.0.tar.gz (1148 bytes)
      1148  [100.00%]
Extracting archive file ...
Archive extracted.
Running setup file ...
PipError('cannot locate source folder/file: /private/var/mobile/Containers/Data/Application/2FDF8EB1-7BD8-4F6B-BF13-835FD5626CA9/tmp/c94a7735c38f47a3b7098ff3def7eaae/sklearn-0.0/wheel-platform-tag-is-broken-on-empty-wheels-see-issue-141.py',)
Failed to run setup.py
Fall back to directory guessing ...
Error: Cannot locate packages. Manual installation required.
--------------------------------------------------------------------
Is there any solution to solve this problem？

**Comment by dgelessus** [comment]
[`sklearn`](https://pypi.python.org/pypi/sklearn) is not the correct PyPI package name:

> Use [scikit-learn](https://pypi.python.org/pypi/scikit-learn/) instead.

The correct package name is [`scikit-learn`](https://pypi.python.org/pypi/scikit-learn). However, scikit-learn requires SciPy, which is not available in Pythonista, so it's not possible to install scikit-learn in Pythonista.

**Comment by Enjia** [comment]
Thanks a lot!
BTW, is Pythonista suitable for machine learning? Because I'm studying this course~

**Comment by dgelessus** [comment]
That depends on what modules you need. A bunch of modules are preinstalled with Pythonista, but nothing machine-learning-related, I think. You can also install *pure* Python modules yourself (using Stash `pip`, or by manually copying the module files into `site-packages`), but you cannot install extension modules that use native code (C, C++, Assembly, Fortran, etc.). Apple has strict requirements about how native libraries have to be signed, which makes it impossible to use any native libraries in Pythonista, unless they came with iOS or the app itself.

**Comment by tchy** [comment]
and why？
[~/Documents]$ pip install pypng
Querying PyPI ... 
Downloading package ...
Opening: https://pypi.python.org/packages/2f/b1/c8dfcf50feb12a30be7d95c5f45d638704682487d8e50419ef41463febcd/pypng-0.0.18.tar.gz
Save as: /private/var/mobile/Containers/Data/Application/266D588E-6FF6-4CD4-A25D-542961114B7E/tmp//pypng-0.0.18.tar.gz (377942 bytes)
    377942  [100.00%]
Extracting archive file ...
Archive extracted.
Running setup file ...
IOError(2, 'No such file or directory')
Failed to run setup.py
Fall back to directory guessing ...
Error: Cannot locate packages. Manual installation required.
