### ISSUE TITLE
How to run command in stash

### ISSUE THREAD

**Issue by JamesHopbourn** [ywangd/stash#244]
Hello,I want to run some command in Pythonista.I was imported the "class-dump" file into Pythonista.But it seems can't running.How can i running command on Pythonista?
![img_0297](https://cloud.githubusercontent.com/assets/18232831/26387225/5ef40fa0-407e-11e7-92fb-91f1f7771cf9.PNG)

**Comment by kiicia** [comment]
you cannot run arbitrary executable file in pythonista, only `.py` files

if it is python file, try `mv class-dump class-dump.py` and then running it by `class-dump` or `./class-dump`

**Comment by Seanld** [comment]
If only iOS wasn't so sandboxed... This is why I love programming on Linux.
