### ISSUE TITLE
stash and running another py file

### ISSUE THREAD

**Issue by kiicia** [ywangd/stash#246]
Running another py file in stash leads to some unexpected things. For example bytes type seems not to be working.

As I understand it is due to iOS blocking creating another thread and effectively it is reinterpreting code?

I was implementing [little something today](https://github.com/kiicia/pyxd) and I had to convert bytes to integers and use only class methods that references self as first argument.

**Comment by Seanld** [comment]
Sounds like a huge issue. I have a question though: why are you running a Python program through StaSh in the first place? That's what Pythonista's for...

**Comment by jsbain** [comment]
Keep in mind when you run a script in stash, it runs in the 2.7 interpreter.
bytes is a py3 thing.

**Comment by kiicia** [comment]
@Seanld because stash has working terminal emulator (pythonista does not) and I was trying to write terminal apps on mobile without outside connection, for example https://github.com/kiicia/pyxd

@jsbain you are right, I have forgotten that stash is python2 app

**Comment by Seanld** [comment]
@kiicia ah okay. That makes sense.

**Comment by Seanld** [comment]
@jsbain are we expecting a Python 3 edition anytime soon?

**Comment by jsbain** [comment]
the py3 branch works for a lot of things.  I have started porting over the git to remove the gittle dependency, which should allow git on py3 as well. 
https://github.com/ywangd/stash/issues/179
