### ISSUE TITLE
Git problems 

### ISSUE THREAD

**Issue by joereddington** [ywangd/stash#247]
I'm enjoying both pythonista and staSh. Both excellent work. I'm having a few problems with git though. Here's what's happening: 

![img_9154](https://user-images.githubusercontent.com/4369547/27760896-3e307e04-5e4a-11e7-9cf4-c9741e3ee7ae.PNG)

Any ideas what I am doing wrong?

**Comment by mikaelho** [comment]
The url needs to end with '.git'

And before you try again 'rm -r .git' as it has already created something there that will block your next attempt.
