### ISSUE TITLE
A native programming language

### ISSUE THREAD

**Issue by Seanld** [ywangd/stash#250]
I was thinking about how the GNU/Linux system has Bash as it's main shell, right? And you can write shell scripts that run natively on the system, without any other dependencies. What if we created our own language that runs natively with StaSh that could have easy access to StaSh's internals so you can program StaSh, and use it as a normal language as well? I've been interested in creating languages, interpreters, and compilers lately, so I can kickstart the project.

Anyone else on board with this idea? I think that it would be really useful.

**Comment by Seanld** [comment]
If you want an example of my progress in programming language construction, I have my first language over at https://github.com/Seanld/py-zm.

**Comment by jsbain** [comment]
stash already supports a limited type of .sh scripts (i.e, pure sequence of stash commands).

**Comment by Seanld** [comment]
@jsbain exactly. So what if there was an actual dynamic language?

**Comment by jsbain** [comment]
We have one... called python ;)

**Comment by Seanld** [comment]
@jsbain yeah I was waiting for that.
