### ISSUE TITLE
Cowsay for stash

### ISSUE THREAD

**Issue by sdushantha** [ywangd/stash#254]
How cool would it be if we could have the good old cowsay command in stash? Well I've made a script which does that! I haven't uploaded it to GitHub yet, because I have some testing to do. But it will be up very soon!
![img_0118](https://user-images.githubusercontent.com/27065646/28745499-d51baed4-7479-11e7-8a52-664b72518e43.PNG)

**Comment by Seanld** [comment]
Seems like a cool project. Make sure to close this issue once it's finished!
