### ISSUE TITLE
Cannot install python3 library 

### ISSUE THREAD

**Issue by Jortana** [ywangd/stash#261]
For example, I just `pip install beautifulsoup4` and it works
But when I `from bs4 import BeautifulSoup`
I got a problem. 
It says I try run python2 code in python3
How to solve it?

**Comment by Seanld** [comment]
I don't know if StaSh supports this, but if you run `pip3` on actual
computer shells, it allows you to install Python 3 packagea and modules.
The reason it won't work is because `pip` installs Python 2 packages due to
StaSh being written in Python 2.

**Comment by Jortana** [comment]
It seems not work.

在 2017年8月5日，05:13，Sean Wilkerson <notifications@github.com<mailto:notifications@github.com>> 写道：

I don't know if StaSh supports this, but if you run `pip3` on actual
computer shells, it allows you to install Python 3 packagea and modules.
The reason it won't work is because `pip` installs Python 2 packages due to
StaSh being written in Python 2.

**Comment by Seanld** [comment]
Yeah `pip3` doesn't work on StaSh. You may need to just install Python 2 modules.

**Comment by Jortana** [comment]
I will be so excited If someone could add pip3.
But now I just copy the folder from my computer.


On 5 Aug 2017, at 07:53, Sean Wilkerson <notifications@github.com<mailto:notifications@github.com>> wrote:


Yeah pip3 doesn't work on StaSh. You may need to just install Python 2 modules.

**Comment by Seanld** [comment]
@Jortana the problem is that StaSh itself is written in Python 2, so making a `pip3` which installs Python 3 modules is kind of difficult. Especially if you want to _use_ those modules in StaSh. You'll probably just get errors.
