### ISSUE TITLE
Attempting to install packages always results in an error

### ISSUE THREAD

**Issue by GiacomoLaw** [ywangd/stash#274]
```
Exception installing mp_compile, proceeding without:[Errno 1] Operation not permitted
TypeError("unsupported operand type(s) for +: 'OmniClass' and 'list'",)
Failed to run setup.py
Fall back to directory guessing ...
Error: Cannot locate packages. Manual installation required.
```

Got this trying to install Pillow, Scraper, and more

**Comment by homecoder** [comment]
What package(s) arenyou trying to install?

**Comment by eheinz** [comment]
I have seen this come up several times, it's always been when I tried to use pip to install an app that was already bundled (ie listed in PYTHONISTA_BUNDLED_MODULES)

**Comment by homecoder** [comment]
@eheinz,

I've also seen this on packages which are not included in the bundled modules.

The pip application could probably use an update, I've had intentions of doing so a hundred times but never got around to it.  I think I will soon though.
