### ISSUE TITLE
Unable to launch_stash.py in pythonista 3 for IOS

### ISSUE THREAD

**Issue by siulman** [ywangd/stash#281]
Hello guys,

I have an ipad pro 10.5 with IOS 11.1 and just downloaded pythonista 3. I want to import some libraries as netmiko with “pip install netmiko”. It appears the best way is with “stash”. So I imported stash with the script: 
import requests as r; exec(r.get('http://bit.ly/get-stash').text)

However, when I try to launch “launch_stach.py” from my home directory I get an error on line 28 “from stash import stash” that says “not well-formed (invalid token). Please, check snapshot attached. 
![bb5b68a6-45fa-4eb6-8320-7d1ee4825149](https://user-images.githubusercontent.com/20261051/33188158-bdacfb66-d097-11e7-9c32-5dfd7d162558.png)

If I try to go to “site-packages” —> “stash” and then execute “stash.py” I get an error “No module named “configParser”.

![0f9f5d83-3e59-4b61-ab67-5424c96be0bd](https://user-images.githubusercontent.com/20261051/33188203-445b0432-d098-11e7-861b-8f4f80bf54d9.png)

Of course, I tryed to restart pythonista 3 but it didn’t fix the issue.

Could someone please help?

**Comment by jsbain** [comment]
can you press the Print Traceback button, and paste the results here?
You may ant to empty out your site packages folder, restart (force quit) pythonista, and try to reinstall stash.

**Comment by jsbain** [comment]
What pythonista version are you running?
The problem seems to be that the Info.plist is malformed...

**Comment by siulman** [comment]
Hi @jsbain , thank you for respond.
Just fyi, I tryed to run either in python 3 and python 2 as the APP allow to change btween the 2 versions and decide wich one you want to use to run sripts.

Here is the result of the of Traceback button:

![613d4980-f959-4ab0-9306-6fdd5ec11bc2](https://user-images.githubusercontent.com/20261051/33198078-480a5370-d0e9-11e7-9d73-83f2bcc6e7ea.png)

I already tryed to empty everything, restart the app, etc... in fact, stash was the first module I installed in Pythonista 3 even before writing a single script....
The only « site package » that I have on my own is the « stash » one...

I am using pythonista v3.0 (300018)

What can I do?

**Comment by siulman** [comment]
When running with Python 2.7, the error message is slight different. Here below:

![c6964961-0a2e-445f-8e0d-6cf30bf9f1d8](https://user-images.githubusercontent.com/20261051/33198527-e0b02724-d0eb-11e7-8041-018213351bba.png)

**Comment by bazbt3** [comment]
Try the instructions from @CodyKochmann's gist, it worked first time for me (and I never gave thanks):

https://gist.github.com/CodyKochmann/4d6b40e77ba862e634185a038d2c3f13

FYI: I don't know if you must remove the current StaSh directory before re/installing, I'm a complete noob.
