### ISSUE TITLE
failed to pip install pyttsx3

### ISSUE THREAD

**Issue by uncompleted** [ywangd/stash#282]
could you help me to solve this problem?
the error message said 'Error: Cannot locate packages. Manual installation required.'
but i really don't know how to do.
many thanks!!
------------------------------------------------------
[~/Documents]$ pip install pyttsx3
Querying PyPI ... 
Downloading package ...
Opening: https://pypi.python.org/packages/24/4e/580726c73272344d3e74b7aaffae55ff6b6450061fbecb8cc6e112531c02/pyttsx3-2.7.tar.gz
Save as: /private/var/mobile/Containers/Data/Application/A8F0EBC8-A0FA-4253-ADEA-45FB9ED71C59/tmp//pyttsx3-2.7.tar.gz (23598 bytes)
     23598  [100.00%]
Extracting archive file ...
Archive extracted.
Running setup file ...
Package installed: pyttsx3
Installing dependency: pyobjc[('>=', '2.4')]
Querying PyPI ... 
Downloading package ...
Opening: https://pypi.python.org/packages/4f/00/de0b0d0b140a34ba2581031dcefe7b826ac06a27152b4c9554cc83d505af/pyobjc-3.1.1.tar.gz
Save as: /private/var/mobile/Containers/Data/Application/A8F0EBC8-A0FA-4253-ADEA-45FB9ED71C59/tmp//pyobjc-3.1.1.tar.gz (3693 bytes)
      3693  [100.00%]
Extracting archive file ...
Archive extracted.
Running setup file ...
PipError('failed to find packages or py_modules arguments in setup call',)
Failed to run setup.py
Fall back to directory guessing ...
Error: Cannot locate packages. Manual installation required.

**Comment by jsbain** [comment]
pyobjc is not compatible with pythonista.

it may be possible to use objc_util to do what pyobjc was doing, but would require you to write some wrappers.

what are you trying to do?  have you looked at the `speech` module in pythonista?

**Comment by uncompleted** [comment]
Thanks for helping, actually the speech module is not good enough for Mandarin, but it's ok, I'm now using an API from Chinese voice supplier.
