### ISSUE TITLE
Pip install to many values to unpack

### ISSUE THREAD

**Issue by diaprogrammer34** [ywangd/stash#285]
when i run (in stash) 
pip install git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]
Gives me this error:
stash: <type 'exceptions.ValueError'>: too many values to unpack
Any solutions? Anything to help would be greatly appreciated

**Comment by jsbain** [comment]
pythonista pip doesnt work that way. 

pip install Rapptz/dischord.py might work.

voice almost certainly wont, since it requires libsodium, which is not present in ios

**Comment by Jerry12798** [comment]
So I have the same issue and ```pip install Rapptz/discord.py``` works however we want the rewrite version. It doesn’t matter if it has voice support or not
