### ISSUE TITLE
Is there an official way to detect pip stash during installs?

### ISSUE THREAD

**Issue by CodyKochmann** [ywangd/stash#289]
I have a package that is python 2 and 3 friendly but in my install script I include `future` if the installer happens to be running python 2 for specific edge cases that make python 2 scream unless `future` is installed. 

When stash runs the install, the setup sees python2 and decides to add `future` to the requirements which then breaks pythonista entirely. 

Im open to any suggestions for something specific my install script can look for to detect that its running in pythonista. (Like a path or a permission or a library sitting in sys.modules) Ive already tried a few methods and am not done hunting for a solution but figured nows a good time to ask if you know of anything since this literally is the only python setup in linux/windows/osx that seems to have this problem.

Thanks for your help in advance.

**Comment by jsbain** [comment]
when inside stash, stash will be in sys.modules...
