### ISSUE TITLE
How pip install pypng

### ISSUE THREAD

**Issue by YKevin0x61** [ywangd/stash#291]
[~/Documents]$ pip install pypng
Querying PyPI ... 
Downloading package ...
Opening: https://pypi.python.org/packages/2f/b1/c8dfcf50feb12a30be7d95c5f45d638704682487d8e50419ef41463febcd/pypng-0.0.18.tar.gz
Save as: /private/var/mobile/Containers/Data/Application/3A894DB8-B91F-4F2B-981E-2CEE5A2B6572/tmp//pypng-0.0.18.tar.gz (377942 bytes)
    377942  [100.00%]
Extracting archive file ...
Archive extracted.
Running setup file ...
IOError(2, 'No such file or directory')
Failed to run setup.py
Fall back to directory guessing ...
Error: Cannot locate packages. Manual installation required.
[~/Documents]$

**Comment by mikaelho** [comment]
Not all packages can be installed with pip on Pythonista, often because they contain C components. You would need to find the source and, if it is just Python, manually downloading and placing in site-packages may work.

**Comment by YKevin0x61** [comment]
Thank you

**Comment by cclauss** [comment]
https://github.com/drj11/pypng is a pure Python package.
