### ISSUE TITLE
Stop update?

### ISSUE THREAD

**Issue by yjqiang** [ywangd/stash#292]
The project has not been updated for a long time, so ... ?

**Comment by victordomingos** [comment]
There is a new StaSh version here that runs in more recent Pythonista versions:

https://github.com/ywangd/stash

This old branch is for legacy Pythonista 1.5.

**Comment by victordomingos** [comment]
Well, while typing on small screen I just failed to notice it's still the same repository, only different branches. Sorry. In fact StaSh development seems to be a little quiet in the last months. I hope the project can get some fresh air soon and become even better, as it's an essential tool for Pythonista.

If you are using the last stable release, maybe trying the dev version may be useful (`selfupdate dev`).

**Comment by yjqiang** [comment]
So glad to hear that since it's an amazing project. By the way, do you have the plan to support python3.6?
