### ISSUE TITLE
Simplifying access to the global variable _stash

### ISSUE THREAD

**Issue by cclauss** [ywangd/stash#298]
Would it make sense to unify they way that scripts in this project access the global variable ___stash__?  There was much discussion on this topic in #295

Perhaps the [get_stash() function](https://github.com/ywangd/stash/blob/master/lib/stashutils/core.py#L9-L23) in `lib/stashutils/core.py` should be moved into `stash.py` or __from stash import \_stash__ should be enabled.

What is the best approach that is intuitive for both humans and linters that avoids the [__\_stash = globals()['\_stash']__](https://github.com/ywangd/stash/search?q=globals()&type=Code) hack that currently pervades this codebase?

**Comment by dgelessus** [comment]
I'm all for `from stash import _stash`. Less magic is better :)
