### ISSUE TITLE
`pip install python-ev3` with StaSh v0.7.0 doesn’t seems to be working...

### ISSUE THREAD

**Issue by GalvinGao** [ywangd/stash#320]
Connection to GitHub, pypi.org, and pypi.python.org are checked to be ok.
System Information:
StaSh Version: **v0.6.20**
Modal: **iPad Pro, iOS 11.3.1 (15E302)**
Pythonista: **v3.2**
Python: **v3.6.1**

I've printed out the url I've got from pypi.org, which is **ended with .egg**.
In **/bin/pip.py:987** I've add `print('  - Download Url : %s' % download['url'])` to print out the download urls.

![09ed01d5-3c86-4510-bbc9-6608217d4cc0](https://user-images.githubusercontent.com/12567059/39680909-7b748c1a-51d8-11e8-9993-fd538546d6f5.png)

**Comment by bennr01** [comment]
@GalvinGao StaSh uses a custom implemented `pip` command which does only support source distributions (`.tar.gz`) and does not support `.wheel` and `.egg` files. Or did `pip install python-ev3` work in StaSh `0.6.20`?

**Comment by GalvinGao** [comment]
It **WORKED** in StaSh `0.6.20`. But I don't guaranteed that either the pypi.org is changing around there file type or the module developer might did...
I have just tried to install `asyncio`, which provides `.whl` and `.tar.gz` and I saw that StaSh has chosen the `.tar.gz` file, which finally installed the modules successfully.
It might because the developer of the module changed the file type...

Is there any workaround that can make `.egg` file working?
![e1ff8d8c-d021-49b4-bf7a-c111b8ed7732](https://user-images.githubusercontent.com/12567059/39689124-1e440d42-5208-11e8-859c-91db8db621d7.jpeg)

**Comment by bennr01** [comment]
@GalvinGao for all eggs, no. But you can try to install the egg manually:
```sh
wget https://files.pythonhosted.org/packages/fa/bb/419b4e2fb03a107b101658147c90b1d6c2704b03886058385bb8e17073b1/python_ev3-0.0.3.0-py3.4.egg
unzip python_ev3-0.0.3.0-py3.4.egg -d $STASH_ROOT/../../site-packages-3/
```
(the above code is untested, but it should install `python-ev3` for python3)

**Comment by GalvinGao** [comment]
I uploaded the wrong image lolllllllllllll😅
I'll try to do that.

**Comment by GalvinGao** [comment]
Successfully installed it. Thanks a lot for help!
