### ISSUE TITLE
Change git password

### ISSUE THREAD

**Issue by TheLastDestroyer** [ywangd/stash#328]
Just changed my github password but can’t for the life of me find where to change it in stash. Tried to follow the code backwards but have got nowhere.

I’m trying to clone a private github repo if it helps

**Comment by TheLastDestroyer** [comment]
Did that, still throwing a 401 error when I try to clone and I also noticed I’m now getting the following error on pushing (to a public repo)

stash: <type 'exceptions.AttributeError'>: 'function' object has no attribute 'urlparse'

**Comment by jsbain** [comment]
as a temporary workaround, in bin/git.py, at line 391, change
config = repo.repo.get_stackedconfig()
to
config = repo.repo.get_config()

**Comment by jsbain** [comment]
Also, implement the fix in #332:  search and replace all urlparse.urlparse with simply urlparse.

**Comment by TheLastDestroyer** [comment]
Thanks, I'll give it a go

**Comment by jsbain** [comment]
Okay, #333 fixes the first issue as well.

**Comment by TheLastDestroyer** [comment]
Ok given it a go, done the find and replace but my git.py (python modules/site-packages/stash/bin/git.py) does not have that on line 391 or in it at all, any get config is already config = repo.repo.get_config().

Cloning a non private repo now works under python 2.7 though is completely silent, still fails under python 3 complaining about no module called urlparse (though this is a separate issue).

Committing also still has the same problems

I am still unable to clone a private repo with the same dulwich 401 error

**Comment by TheLastDestroyer** [comment]
I feel this issue has got out of hand though, I’m closing this (I’ve fixed my password) and will open sone new issues.
