### ISSUE TITLE
Tensorflow install with pip error

### ISSUE THREAD

**Issue by SmartGoat38** [ywangd/stash#343]
Got this strange download error from the command `pip install tensorflow`:
![b82d35ea-469a-487c-b821-50410b7c8603](https://user-images.githubusercontent.com/35306962/49111918-bd01ed80-f291-11e8-910a-d1c51e6b8a05.jpeg)
Stash Version: 0.7.1
Python: 3.6.1
Thanks in advance

**Comment by bennr01** [comment]
StaSh pip only works with pure python packages. `tensorflow` has c-dependencies, which are not supported by pythonista.

**Comment by SmartGoat38** [comment]
Well, it’s sad, but anyway, thank you
