### ISSUE TITLE
Cannot use spacebar with german smart keyboard folio

### ISSUE THREAD

**Issue by marzig** [ywangd/stash#356]
Hi everybody!

Just bought the smart keyboard folio for my iPad Pro 11 and discovered that it‘s not possible to use the space key while using stash. This is the first app where this problem occurs.
Don‘t know if it is relevant but my smart keyboard folio has a german layout.
Anyone else experienced this problem?

Kind regards

**Comment by jacquescousteau** [comment]
Having this same issue. Have a US Smart Keyboard folio, 11” iPad Pro. Running beta Pythonista. No spacebar in StaSh running in python 3.6 or 2.7.

**Comment by bennr01** [comment]
Hi,

I investigated this bug a few weeks ago. It seems like the new pythonista beta does not call the delegates correctly. Since this seems to be a pythonista bug, I have opened a pythonista issue [here](https://github.com/omz/Pythonista-Issues/issues/597)

**Comment by marzig** [comment]
Closed since this seems to be a pythonista bug.
