### ISSUE TITLE
Pythonista 3.3 Install

### ISSUE THREAD

**Issue by Jerry12798** [ywangd/stash#360]
So I ran ```import requests as r; exec(r.get('https://bit.ly/get-stash').text)``` then restarted Pythonista. Once in ```site-packages``` I don’t see ```launch_stash.py``` as the directions say. I have tried deleting the Stash directory and rerunning the ```stash_installer.py``` script however every time it does the same thing. I’ve searched all the folders in Stash directory however none have ```launch_stash.py``` I am using iOS 12.0.1 and Pythonista 3.3 beta

**Comment by bennr01** [comment]
'launch_stash.py' should be in the Pythonista root directory.

**Comment by Jerry12798** [comment]
I don’t see it there either
https://imgur.com/a/MgEfshh

**Comment by Jerry12798** [comment]
Here are all my screenshots.. couldn’t seem to attach them here.
https://imgur.com/a/LCK5rdK

**Comment by bennr01** [comment]
You are in the wrong directory. Force quit pythonista, the start it again, choose 'this iPhone' (or whatever device you have). This directory should contain 'launch_stash.py'.

**Comment by Jerry12798** [comment]
Thanks so much 😁
