### ISSUE TITLE
Cannot clone repos with git

### ISSUE THREAD

**Issue by MaxNacemit** [ywangd/stash#361]
When I use git clone, stash returns “no module named urlparse”.  The problem is, this module cannot be installed as it is python2-only.

**Comment by jsbain** [comment]
Run launch_stash in py2.  For various reasons, stash git isn't fully supprted in py3 yetOn Mar 19, 2019 12:54 AM, Maxim Kuzmin <notifications@github.com> wrote:When I use git clone, stash returns “no module named urlparse”.  The problem is, this module cannot be installed as it is python2-only.
