### ISSUE TITLE
How to use git in Pythonista 3 or stash? 

### ISSUE THREAD

**Issue by kaixinbaba** [ywangd/stash#369]
When I run lauch_stash.py into shell console, and do command 'git -h' or other git cmd, the shell shows start to install some lib, but finally failed, and display 'No module named urlparser',
so I try to use another command 'gh -h', I think it will may be worked, but also got exception 'No module named Requester', so I use 'pip install requests requester', both success, and ran into python3 console, run 'import requests' and 'import requester' both success too. Then I try 'gh -h' again, got same exception~ Please help me, if I can't use git to pull my code, the Pythonista3 is not good enough for me. Or there is another way may let me copy code into my iphone and also can get it out~

**Comment by jsbain** [comment]
At the start of launch_stash, add #!python2If you are using a recent iOS version, you may be happier installing WorkingCopy app, which has a more robust git implemention and has pythonista integration.  The stash git, while functional, is limited and finicky.On Apr 13, 2019 7:57 AM, Jeff Xun <notifications@github.com> wrote:When I run lauch_stash.py into shell console, and do command 'git -h' or other git cmd, the shell shows start to install some lib, but finally failed, and display 'No module named urlparser',
so I try to use another command 'gh -h', I think it will may be worked, but also got exception 'No module named Requester', so I use 'pip install requests requester', both success, and ran into python3 console, run 'import requests' and 'import requester' both success too. Then I try 'gh -h' again, got same exception~ Please help me, if I can't use git to pull my code, the Pythonista3 is not good enough for me. Or there is another way may let me copy code into my iphone and also can get it out~

**Comment by kaixinbaba** [comment]
I tried to "add #!python2If you are using a recent iOS version" at launch_stash.py script, the command 'git -h' is display normal, but when I use 'git clone https://github.com/xxxxxxxxxxx.git', I got another exception "<class 'dulwich.errors.GitProtocolError'>: unexpected http response 401", what's the reason?
And I tried the app 'Working Copy', it's a perfect app to pull my repository code to my Iphone, but how can I use 'Working Copy' and 'Pythonista3' together? Or how to open the folder in 'Pythonista3' from 'Working Copy'?
Thank you for your answer.
Using git is the most important thing~
And by the way, I bought a Bluetooth keyboard code for pythonista3. Can I use VIM mode after I connect the Bluetooth keyboard?

**Comment by TeamSpen210** [comment]
In Pythonista's top-level file menu there's a button labeled "open" in the "external files" section. Press that, then you'll need to enable Working Copy as a location. You can then browse into the desired repo and pick a file, or press the "select" button to let you pick a folder and open it. Once that's done, it'll appear a menu option in the "external files" section, and you can edit/run code just like anywhere else. The files/folders are shared, so changes in either will affect the other.

**Comment by kaixinbaba** [comment]
@TeamSpen210 I got it! Thank you very much
