### ISSUE TITLE
pip install aiohttp error: class 'FileNotFoundError'>: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by yjqiang** [ywangd/stash#370]
pip.py: error: unrecognized arguments: -verbose
[~/Documents]$ pip --verbose install aiojobs
Querying PyPI ... 
Using aiojobs==0.2.2...
A binary distribution is available and will be used.
Downloading package ...
Opening: https://files.pythonhosted.org/packages/a7/8e/1d41d21e7cd09d744921490be99a9e2cfa498ae1af36b9c3ee0c3395d2c9/aiojobs-0.2.2-py3-none-any.whl

Save as: /private/var/mobile/Containers/Data/Application/106690BE-96ED-4657-8531-E99119A7CD8F/tmp//aiojobs-0.2.2-py3-none-any.whl (24664 bytes)
     24664  [100.00%]
Installing wheel: aiojobs-0.2.2-py3-none-any.whl...
Extracting wheel..
Extraction finished, running handlers...
Running handler 'WHEEL information checker'...
Wheel generated by: flit 1.2.1
Running handler 'dependency handler'...
Running handler 'top_level.txt installer'...
Cleaning up...
<class 'FileNotFoundError'>: [Errno 2] No such file or directory: '/private/var/mobile/Containers/Data/Application/106690BE-96ED-4657-8531-E99119A7CD8F/tmp/wheel_tmp/aiojobs-0.2.2-py3-none-any.whl/aiojobs-0.2.2.dist-info/top_level.txt'

**Comment by yjqiang** [comment]
https://github.com/aio-libs/aiojobs/issues/105#issuecomment-493360619
So I think we should generate a top_level.txt? Or anything?

**Comment by bennr01** [comment]
Thanks for the bug report. For the time being, you can use `pip --verbose install --no-binary :all: <package>` to disable wheels for the installation.

**Comment by yjqiang** [comment]
> Thanks for the bug report. For the time being, you can use `pip --verbose install --no-binary :all: <package>` to disable wheels for the installation.

So we should remove the wheels? Or try to fix it?

**Comment by bennr01** [comment]
I think we should attempt to fix it. IIRC the average compatibility greatly improved after adding support for wheels.

**Comment by yjqiang** [comment]
@bennr01 Here is my solution. But I'm not sure about this. https://github.com/ywangd/stash/issues/372

**Comment by yjqiang** [comment]
So I think we can close this issue and go to #372 to talk about fixing wheels?

**Comment by yjqiang** [comment]
https://github.com/ywangd/stash/pull/373
