### ISSUE TITLE
UnicoDecodeError from pip

### ISSUE THREAD

**Issue by boxed** [ywangd/stash#381]
If I try to install tri.token it crashes. The fix is already in the code base but commented out! 

https://github.com/ywangd/stash/blob/master/bin/pip.py#L775

**Comment by bennr01** [comment]
The problem with line 775 is that sometimes a `setup.py` (or any other .py file) has an encoding specified. Basically, we either need a binary string with an encoding line or an unicode string without an encoding line. Otherwise, we get some encoding related exceptions.
The problem is how to detect the correct way to open/read the file.

**Comment by boxed** [comment]
Sure. But from what I can tell the current code decodes ascii. This is the worst possible guess! Utf8 will be correct in a big superset of cases (a set that grows every day!). Changing the code to use utf8, at least under python 3,  will be a big improvement with no downside.

**Comment by dgelessus** [comment]
I think it would be best to read the file as bytes (i. e. mode `"rb"`) and pass the byte string to `ast.parse` without trying to decode it. That way Python's parser will recognize the encoding comment in the source code and decode it using the correct encoding.

**Comment by bennr01** [comment]
@dgelessus you beat me ;( i was just writing the same, but in a more crude english.

**Comment by boxed** [comment]
Oh. That sounds 100% better!

**Comment by boxed** [comment]
This is still a thing btw.

**Comment by onyxware** [comment]
I have tested the fix that @dgelessus suggested, and it looks like this:

(current source code)
```
with open(filename, "r") as ins:
    s = ins.read()
tree = ast.parse(s, filename=filename, mode='exec')
```

(fixed source code)
```
with open(filename, "rb") as ins:
    tree = ast.parse(
        ins.read(),
        filename=filename,
        mode='exec'
    )
```

And sure enough, `tri.token` can now be installed:

```
[~/Documents]$ pip install tri.token
Querying PyPI ... 
Downloading package ...
Opening: https://files.pythonhosted.org/packages/77/3b/2bb60e1cd18661c5023217994fc45fe842dd1d85f710e2eeef7d33a94481/tri.token-3.1.1.tar.gz

Save as: /private/var/mobile/Containers/Data/Application/B003D520-C2B7-4AB4-85BB-A3249C3C1D78/tmp//tri.token-3.1.1.tar.gz (9067 bytes)
[====================] 100.00% | 8.9KiB          
Extracting archive file ...
Archive extracted.
Running setup file ...
Package installed: tri.token
... (installing dependencies here)
```

I will commit this fix to my StaSh fork and submit a pull request to `ywangd/dev` by today.

**Comment by boxed** [comment]
Thanks!
