### ISSUE TITLE
Pythonista 3 pip error

### ISSUE THREAD

**Issue by PixelAgent007** [ywangd/stash#383]
I just buyed Pythonista 3 and installed Stash. I installed the Module wikipedia with pip and tried to install PyAudio, Portaudio and SpeechRecognition. I want to make a virtual Assistant, but without these Modules I cant do anything.

Please Help

Error if I try to run pip:
`stash: <class 'IsADirectoryError'>: [Errno 21] Is a directory: '/var/mobile/Containers/Data/Application/8123D864-703B-4257-8672-627C63837817/Documents/site-packages-3/.pypi_packages'`
![802906A5-CB05-4F23-BA52-272CF0B4664A](https://user-images.githubusercontent.com/52569953/60720867-5d0cad00-9f2c-11e9-802e-7538b14e07ea.png)

**Comment by mikaelho** [comment]
Have you looked at the built-in speech module?

**Comment by PixelAgent007** [comment]
I dont know about a built-in speech module, but for Speech Output I use os.popen(say "text")

**Comment by jsbain** [comment]
PyAudio and portaudio are C extensions. You cannot use those on iOS.
Nor can you use os.popen.  
Not sure about SpeechRecognition -- it might work with google cloud api.  

pythonista comes with built in speech tools that are supported on iOS (you might need to install the beta), or you can use ObjC.  several example are on the forums

**Comment by PixelAgent007** [comment]
Thanks

But do you know how to fix the pip error; everything I try to install with pip does not work?

**Comment by PixelAgent007** [comment]
And whats about pyttsx3? Is that C too?

**Comment by bennr01** [comment]
@PixelAgent007 

> But do you know how to fix the pip error; everything I try to install with pip does not work?

Try running `rm -r $HOME2/site-packages-3/.pypi_packages`

> And whats about pyttsx3? Is that C too?

It is not C but appears to depend on other packages which may not work. I am not sure if `pyobjc` can be replaced with pythonistas objc-support.

**Comment by PixelAgent007** [comment]
![5C6B8D0E-2380-40A4-8BD1-3DD1630841C3](https://user-images.githubusercontent.com/52569953/60737108-d5d62e00-9f59-11e9-9462-66f9d5b04de5.png)

**Comment by PixelAgent007** [comment]
Thank you all

It worked!

**Comment by PixelAgent007** [comment]
Now I know how to solve this error. If I install pyttsx3, nothing goes wrong, but if I uninstalled it, the error appeared. But with the fix by @bennr01 everything works fine. But I have to find another way for Speech Output.

Does anyone have an idea??

**Comment by bennr01** [comment]
@PixelAgent007 `import speech; speech.say("Hello, World!")` or something like this should work, like suggested by @mikaelho

**Comment by PixelAgent007** [comment]
Thanks a lot.

**Comment by PixelAgent007** [comment]
WHY!!!
![C32708C6-70B5-46AA-9DC0-FFF7FFD087B1](https://user-images.githubusercontent.com/52569953/60737874-88a78b80-9f5c-11e9-8a3f-696538072186.png)

**Comment by jsbain** [comment]
See
https://forum.omz-software.com/topic/5491/implementing-live-voice-commands/29
For the best pythonista methods for real time recognition.

The somewhat undocumented speech.recognize also works for files recorded by sound.Recorder, but not in real time.

**Comment by PixelAgent007** [comment]
I just wanted to test it, and it DOES NOT WORK!!!
![EA01217A-C2FB-445D-9D22-8D0C9BDA563C](https://user-images.githubusercontent.com/52569953/60738171-af19f680-9f5d-11e9-8179-f4c6619b741d.png)

**Comment by PixelAgent007** [comment]
Maybe I'm just too stupid for that....

**Comment by PixelAgent007** [comment]
> See
> https://forum.omz-software.com/topic/5491/implementing-live-voice-commands/29
> For the best pythonista methods for real time recognition.
> 
> The somewhat undocumented speech.recognize also works for files recorded by sound.Recorder, but not in real time.

I dont understand this thread. It‘s confusing.

**Comment by jsbain** [comment]
What iOS version are you running?  SFSpeechRecognizer was introduced in iOS10.  
Post to the forums, the author of the example may be able to help

**Comment by PixelAgent007** [comment]
I'm running iOS 12.1 on an iPad Air 2

**Comment by SamyBencherif** [comment]
@PixelAgent007 This command looks like it might help
```bash
touch site-packages-3/.pypi_packages
```

Good luck with your project

**Comment by oskardotglobal** [comment]
@cclauss Sorry for the necro but since you seem to be the most active maintainer of this project, could you delete this issue because this account used to have a different name I don't want to associate with this account anymore. Thanks!
