### ISSUE TITLE
Pip.py list error

### ISSUE THREAD

**Issue by yaroslavyaroslav** [ywangd/stash#387]
In python3 mode `pip.py list` input produces error following error:
`<class 'KeyError'>: 'summary'`
![524C761B-9A5C-463B-AA3F-754A220A673C](https://user-images.githubusercontent.com/16612247/63891641-5c553c00-c9ee-11e9-9e7e-c4aeb0b12f8f.png)

**Comment by bennr01** [comment]
@yaroslavyaroslav This should be fixed in e2dcbf5. To update, use `selfupdate -f dev`. Can you confirm if it works for you?
