### ISSUE TITLE
Pythonista crashes after installing stash [iOS 13.1.3]

### ISSUE THREAD

**Issue by seriousm4x** [ywangd/stash#391]
Steps I did:
* Download Pythonista
* run the install command (with python3)
* close the app in the app switcher
* try to open Pythonista but it’s stuck in the splash screen and after a few seconds it just closes

My Device:
* iPad Pro 12,9 (2018)
* iOS 13.1.3
* Latest Pythonista and Stash

**Comment by cstotzer** [comment]
The same here on a 10-inch 2018 iPad

**Comment by maxrugen** [comment]
Same here on iPad Pro 2018 12.9 on 13.4

**Comment by maxrugen** [comment]
@cstotzer @seriousm4x Are you guys using a cellular model iPad?

As I‘ve noticed, the problem only occurs when the iPad is not connected to a WiFi network, so using either the iPad’s mobile data connection or no data connection at all while launching Pythonista after installing Stash causes the app to crash while launching.

**Comment by seriousm4x** [comment]
I don't have a cellular model and I'm connected to wifi. Still crashes

**Comment by mralexcraven3** [comment]
Same here using 11” 2020 iPad Pro

**Comment by mavjr0313** [comment]
````
#~~~~
````

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by seriousm4x** [comment]
I don't think this is relevant anymore
