### ISSUE TITLE
Pytest deprecation warnings

### ISSUE THREAD

**Issue by cclauss** [ywangd/stash#394]
https://travis-ci.org/ywangd/stash/jobs/608711726#L2017

**Comment by bennr01** [comment]
This should now be *mostly* fixed in the newest `dev` version, but I was unable to find [one of the `DeprecationError`s](https://travis-ci.org/ywangd/stash/jobs/613584431#L2277).

**Comment by cclauss** [comment]
https://github.com/ywangd/stash/blob/dev/bin/monkeylord.py#L34 ??

**Comment by bennr01** [comment]
> https://github.com/ywangd/stash/blob/dev/bin/monkeylord.py#L34 ??

Well, that is indeed one, but since we have no tests for `monkeylord` (yet), that code should never be executed and thus there should be no warnings...
