### ISSUE TITLE
Pip doesn’t work. 

### ISSUE THREAD

**Issue by MaxNacemit** [ywangd/stash#398]
In the latest version of Pythonista, when I tried to “pip install requests”, I got a ModuleNotFound error when running Stash in Python 3 and “no module named pip._internal” when running it in Python 2. What can be causing this?

**Comment by bennr01** [comment]
> `no module named pip._internal`

StaSh's `pip` implementation is single file and has no module `pip._internal`. This indicates one of the following possibilities:

1. You somehow replaced StaSh's `pip` with the normal `pip`.
2. The module/package you want to install wants to access the `pip` internals.

To check if case 1 applies, please check the output of `which pip`. The output should be something like `[...]/Documents/site-packages/stash/bin/pip.py`. If it is something like `[...]/Documents/stash_extensions/bin/pip.py`, you have to remove that file. In this case, also remove any file and directory  called `pip` in the `site-packages`, `site-packages-2` and `site-packages-3` directory. Then force-restart pythonista to clear the module cache.

In case 2, we need more info: which package do you want to install? What is the traceback? To get more information about this, please run `stashconf py_traceback 1` followed by `pip --verbose install [name of package you want to install]` and paste the output here.

**Comment by MaxNacemit** [comment]
It was the first case, now everything works. Thank you!

**Comment by dontbanmeplz** [comment]
mine is idk
