### ISSUE TITLE
Uninstall StaSh

### ISSUE THREAD

**Issue by MaTianlai** [ywangd/stash#399]
How to uninstall StaSh completely? I don’t know how to do that.

**Comment by NatLee** [comment]
Did you try to reinstall pythonista?

**Comment by MaTianlai** [comment]
> Have you tried to reinstall pythonista?
> 
> Or you can delete files on two locations from Pythonista by using your finger with `scrolling to left`:
> 
> * This iPad > `launch_stash.py` and `stash_extensions`
> * Python Modules > site-packages > `stash`

Thank you very much.
