### ISSUE TITLE
Send pull request to dev branch instead of master

### ISSUE THREAD

**Issue by ywangd** [ywangd/stash#40]
@briarfox @dgelessus 
I think it is better to make the master branch relatively stable. Development works are better done in the separate **dev** branch. When we make a release cut, code in dev branch is merged to master. The code in master branch is mostly static except bug fixes (but no new features). I think this setup is more friendly and less confusing to end-users.

Since default `selfupdate` branch is master, as developers, you'll have to config the branch to **dev** via the environment variable `SELFUPDATE_BRANCH`, i.e. put `SELFUPDATE_BRANCH=dev` to your `.stashrc` file.

I'd like to make this happen for the next v0.3.0 release. So please send future pull requests to **dev** branch. Please let me know your thoughts. Thanks!

**Comment by dgelessus** [comment]
OK, I'll make sure to do that in the future. I'm still fairly unexperienced with GitHub, so please bear with me if I do things wrong. (And please tell me as well, otherwise I won't notice for a month or so ;)

**Comment by briarfox** [comment]
@ywangd Will do.

**Comment by ywangd** [comment]
Thank you both! :)
