### ISSUE TITLE
tried to install pipenv

### ISSUE THREAD

**Issue by feelingnothing** [ywangd/stash#418]
'pip install pipenv'
"""

Querying PyPI ... 
Downloading package ...
Opening: https://files.pythonhosted.org/packages/f6/fe/0adf70655fc4b6f0118f22489b3aac80b6f8a2cb38dd4bf071427eb82c14/pipenv-2020.6.2-py2.py3-none-any.whl

Save as: /private/var/mobile/Containers/Data/Application/9D4242A4-32A6-4BF9-81EE-2DF1FE51F4EE/tmp//pipenv-2020.6.2-py2.py3-none-any.whl (3874440 bytes)
[====================] 100.00% | 3.7MiB          
 nstalling wheel: pipenv-2020.6.2-py2.py3-none-any.whl...
Package installed: pipenv
Installing dependency: pip[('>=', '18.0')] (required by: pipenv)
Package pip is blacklisted and marked fatal. Failing install.
Reason: StaSh uses a custom version of PIP. Installing the 'pip' package would likely break StaSh.
Error: Package 'pip' blacklisted. Reason: StaSh uses a custom version of PIP. Installing the 'pip' package would likely break StaSh.
"""

then i installed it manually and tried "pipenv"
"""

stash: <class 'RuntimeError'>: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/python3/ for mitigation steps.

Additional information: on this system no suitable UTF-8 locales were discovered. This most likely requires resolving by reconfiguring the locale system.
"""

this link has solution with export but stash doesn't have export

**Comment by bennr01** [comment]
Hi,

`pipenv`*likely* won't work with StaSh.

> this link has solution with export but stash doesn't have export

Have you tried setting the variable without `export`? Example: `LC_ALL=... mycommand`?

**Comment by feelingnothing** [comment]
Tried it right now, but got the same error,
I tried
```
LC_ALL=C.UTF-8
LANG=C.UTF-8
```
got
```
Click discovered that you exported a UTF-8 locate but the locate system could now pick up from it because it does not exist.
The exported locate is 'C.UTF-8' but it is not supported
```
then i did
```
LC_ALL=UTF-8
LANG=UTF-8
```
got
```
Additional information: on this system no suitable UTF-8 locales were discovered. This most likely requires resolving by reconfiguring the locale system.
```
