### ISSUE TITLE
Export a simple stash run function to external script

### ISSUE THREAD

**Issue by ywangd** [ywangd/stash#43]
So external commands can do something like
```python
_('cp afile bfile')
```
to ask stash to run the command.

**Comment by dgelessus** [comment]
`_` might not be a good naming choice - although being short and simple, it is fairly common practice to use `_` as a "junk" name in sequence unpacking, e. g. `foo, _, bar = somestring.split(";")`. The interactive interpreter also assigns the last result to `_`. Maybe something short but more descriptive like `_sh` or `_shrun`?

**Comment by ywangd** [comment]
@dgelessus I think you got the point. I wanted the name to be less intrusive and focus on the actual command texts. `_sh` seems to be a good alternative.

**Comment by briarfox** [comment]
I think _sh is a good choice. What do you expect the eta on this to the dev branch? I'll scrap the .sh temp creation in pip.

**Comment by ywangd** [comment]
@dgelessus @briarfox 
Since the `_stash` object is already exposed to external scripts. I think it can be reused for this purpose to simplify the overall exported functions. I made `_stash` callable so that a shell command execution can be as follows:
```python
_stash('cp afile bfile')
```
This change is already pushed to the `dev` branch. Comments/suggestions are welcome. Thanks!

**Comment by dgelessus** [comment]
Good idea, I didn't think of that possibility.

**Comment by ywangd** [comment]
The function accepts both mulit-line string, e.g.
```python
_stash('cd dir1 \n cp afile bfile')
```
and list of strings, e.g.
```python
_stash(['cd dir1', 'cp afile bfile'])
```
