### ISSUE TITLE
git clone is something wrong

### ISSUE THREAD

**Issue by udemymaster** [ywangd/stash#430]
I am using StaSh on Pythonista for using GitHub.

It occured when I type command 'git clone URL'.

My GitHub repository name is 'gittest', but  my local repository name it made by 'git clone' was 'gittes'.
'testsomething' also changed 'testsomethin'

So I checked 'bin/git.py'.

line499
```
repo = Gittle.clone(args[0], args[1] if len(args) > 1 else os.path.split(args[0])[-1].rstrip('.git'), bare=False)
```

I guessed coused by rstrip('.git').

if repository name is finished 'g' or 'i' or 't', it delete by rstrip('.git').

I have changed rstrip('.git') to replace('.git', '') then it went well.

but, I don't know how to commit this bug because I'm beginner of GitHub

Please someone confirm this bug and fix 'bin/git.py'

**Comment by ywangd** [comment]
Thanks for reporting. This is now [fixed](#431) and pushed to the `dev` branch.
