### ISSUE TITLE
pillow install error

### ISSUE THREAD

**Issue by jmmelko** [ywangd/stash#433]
Hi,

I have discovered that Pythonista’s pillow version is... 2.9.0 !
So I tried installing pillow 5.2.0 and 6.1.0 with pip-stash and got the following error:
`TypeError("unsupported operand type(s) for +: 'OmniClass' and 'list'",)
Failed to run setup.py
Fall back to directory guessing ...
Error: Cannot locate packages. Manual installation required.`

I believe pillow is one of those blacklisted packages, not because of PyPI compatibility but because it is already bundled (and modified) within Pythonista.
In any case stash-pip should say it.
Pillow is very popular.

**Comment by jsbain** [comment]
The reason you cannot install pillow is because pillow is written in mostly c/c++.  You can only install pure python packages pythonista, since compiled code cannot run on iOS unless signed by the Pythonista developer.

**Comment by jmmelko** [comment]
Ok thank you.

i up for the blacklist idea then. #376
