### ISSUE TITLE
Selenium

### ISSUE THREAD

**Issue by GabrielSestieri** [ywangd/stash#446]
Will there ever be a possibility to download the selenium package? Many packages use Selenium and so those packages don't work because Selenium can't be found and can't be downloaded.

**Comment by thenamesnano** [comment]
Looked into `site-packages/data/pip_blocklist.json` and it has the reason why Selenium is not allowed.  It says Selenium is blocked for process interaction stating, "This package requires process interaction, which is not possible on iOS".  I hope this helps.

**Comment by fschaeck** [comment]
Closing issue since Selenium can not be supported on iOS.
