### ISSUE TITLE
Question:  what does the Sta in StaSh stand for?

### ISSUE THREAD

**Issue by jsbain** [ywangd/stash#48]

**Comment by dgelessus** [comment]
Pythoni**sta sh**ell

**Comment by ywangd** [comment]
Yep what @dgelessus said.

**sta** may not be the best brief for Pythonista but it forms a nice word with the following **sh** part. So I just thought the word reads nicely and kinda have the meaning that it is a confined environment and some awesome treasure could be found within.

**Comment by ywangd** [comment]
I'll add this background info in README. Thanks!

**Comment by ywangd** [comment]
Background section added.
