### ISSUE TITLE
site-packages-3 is now just site-packages

### ISSUE THREAD

**Issue by eddo888** [ywangd/stash#482]
for python 3.10 and pythonista 3.4 please update libdist.py

**Comment by cclauss** [comment]
Dup of #462

Fixed in #480

**Comment by cclauss** [comment]
Fixed on `dev` in https://github.com/ywangd/stash/commit/a882c80d174099382faf937b1ffceaa58bbce584
Fixed on `master` in https://github.com/ywangd/stash/commit/fbdb9cfe8625408f1e3bcb62aa99366debf2f177
