### ISSUE TITLE
KeyboardInterrupt after every command

### ISSUE THREAD

**Issue by korbiniangabriel** [ywangd/stash#507]
**Issue:**
After freshly installing stash on Pythonista3, every single command is followed by a keyboard interrupt. 

**Usage:**
This hinders installations from git and running other commands like pip installing pandas.

**Example:**

[~/Documents]$ ls

launch_stash.py Welcome.md _objc_exception.txt Templates site-packages stash_extensions stash_install.py Examples

**stash: ^C
KeyboardInterrupt: Exit: 0**

**Environment:**
This runs on python 3 with currently no additional modules installed.

**Comment by cclauss** [comment]
Installing Pandas will not work because Pythonista already bundles Pandas.
```
>>> import pandas
>>> pandas.__version__
'1.4.4'
```
