### ISSUE TITLE
Cat barfs on binary files

### ISSUE THREAD

**Issue by jsbain** [ywangd/stash#56]
Binary files make cat unhappy, complaining about UTF8 not being able to decode.  For instance, cat .git/index in a git repo.

Proposed fix, just replace no printable with blanks.  I'm honestly not sure what Unix normally does...or maybe we need a strings command, etc? 
https://github.com/jsbain/stash/commit/95281025af53e4b397bb2a005dae9db301212cbe#diff-0

**Comment by dgelessus** [comment]
For now you can use `printhex`, it prints a file's hex byte values in a hex editor-style table.

**Comment by ywangd** [comment]
@jsbain I coded `cat` in a rush and only had text files in mind. Thanks for the fix. #60 merged. 

@dgelessus That is indeed a great use case for `printhex`. Thanks!

**Comment by ywangd** [comment]
@jsbain I made a minor modification to `cat` so line feed and carriage return can be displayed e99d74227bcaceaf2e99b44515fe99c6d141bc87
