### ISSUE TITLE
Milestone Changes - Unified Input/Output areas with a single TextView

### ISSUE THREAD

**Issue by ywangd** [ywangd/stash#73]
@briarfox @dgelessus @jsbain
I am very excited to announce a major change to the UI design. The user input and output areas are now unified by a **single TextView**. This is more like a real terminal (no more split input and iutput areas). The advantages are significant:

* **No more screen flashing** when scrolling. **Smooth scroll** all the time.
* Tab completion support for **external keyboard** (still working on arrow keys)
* **Cursor position manipulation** (allow symbols from virtual keys to be inserted in the middle of a line)
* A long input line is now easy to manage as it automatically wraps
* **Show/Hide keyboard** easily with a button tap
* Device rotation no longer breaks the UI
* Possible to **emulate text editors** directly in the terminal
* Consistent look and feel to computer terminals

The changes are pushed to a new branch **single-tv**. Please give it a go when convenient (just type `SELFUPDATE_BRANCH=single-tv selfupdate` and restart StaSh afterwards). 

Before merge this branch to dev, I'd like to wrap up current version and tag version 0.3.0 (which will be the last version to have the split UI design). The unified TextView change will be released as version 0.4.0.

Suggestions/comments are welcome.

@briarfox I also made a few changes to `ssh.py` to suit the new UI.

**Comment by briarfox** [comment]
@ywangd That is very impressive. I can't wait to look through the code and see how you accomplished that! Thanks again for all the work you are putting into stash. I find stash a must use with pythonista.

**Comment by ywangd** [comment]
@briarfox Thanks for the nice words. I hope you find the new design more usable than the previous one. I had a lot fun developing this new version.

It is a bit tricky to manage I/O in a single view. The code is rough at this stage. I already have a couple optimizations in mind and will keep improve it when time permits.

**Comment by ywangd** [comment]
d076729372cdc0df4bca0ed5d83d5b2fa8497ed5
