### ISSUE TITLE
Editor mode

### ISSUE THREAD

**Issue by ywangd** [ywangd/stash#83]
Allow text files to be edited directly in the terminal.

**Comment by ywangd** [comment]
Not sure how necessary this is as we have access to Pythonista builtin editor. It might be better to just enhance the user interaction part of  `edit.py`.

**Comment by jsbain** [comment]
as an aside, I've been having lots of trouble with edit -t recently causing pythonista to crash.  Possibly we need a delay before opening editor, or maybe need to hide keyboard first, etc.  anyone have this issue?

**Comment by ywangd** [comment]
I haven't really used the `edit` command as I often use [my own very primitive UI editor](https://github.com/ywangd/ed-pythonista) to edit dot files. 
@briarfox Could you please comment on this?

**Comment by briarfox** [comment]
@jsbain I use edit -t quite a bit and have not experienced a crash. What iPad and iOS are you using?

**Comment by jsbain** [comment]
Ipad 2, iOS 7.1
I need to try this again.  I was trying to edit  $STASH_ROOT/.git/config, if memory serves.

**Comment by Vik2015** [comment]
Hey there. edit (without any options) caused my Pythonista to crash several times in a row. I am using updated version (with delay of 1.5 sec) and my iPad is 3rd.

**Comment by ywangd** [comment]
I cannot reproduce it. Are you using the latest StaSh? Try `selfupdate` and see whether it still crashes?

**Comment by briarfox** [comment]
I can't replicate the issue either. Which pythonista version are you using?

**Comment by ywangd** [comment]
Pythonista 1.6 is much more generous on what files you can open in the builtin editor. It can now open the dot files, e.g. `.stashrc`. So this feature is no longer needed.
