### ISSUE TITLE
Move py_traceback from config to rcfile

### ISSUE THREAD

**Issue by ywangd** [ywangd/stash#85]
So it can be changed on the fly? What about input_encoding_utf8

**Comment by jsbain** [comment]
+1 on the py_traceback
Actually, I'm thinking we maybe should have an on_error flag.  Two options would be print message, print traceback, but a third option would be to run pdb.pm().  Pdb works really well in stash (I'd love to have history available, but I'll open another issue for that).  I tried so something like this, but It didn't seem to work, I think perhaps we need to set the frame or

**Comment by jsbain** [comment]
Ok. I did get post mortems to work.  I added another rc variable! the used the following code

```python
            
        except Exception as e:
            if self.py_traceback:
                import traceback
                traceback.print_exc()
            if self.debug_py:
                import pdb
                pdb.post_mortem(sys.exc_traceback)
```

**Comment by ywangd** [comment]
@jsbain I think the inclusion of pdb is an excellent feature. I had some initial tests and it worked really well. I'll definitely see it in the source code. I may call the option `py_pdb` so it is consistent with `py_traceback` and clearly indicate it calls to pdb. Thanks for the great suggestion!

Now I am thinking these options should still belong to the config file instead of rcfile, as they are options that alter the shell's own behaviour as oppose to the behaviours of the bin commands. To make them modifiable when stash is running, a new "stashconf" command can be added to manage configurations.

**Comment by ywangd** [comment]
The `py_pdb` config option is now added d957f29180fd5e8f87079de4f790fde927d6e210
An initial `stashconf` script is also provided to change config options on the fly.
