### ISSUE TITLE
[feature request] history for subcommands

### ISSUE THREAD

**Issue by jsbain** [ywangd/stash#90]
I'll admit I haven't looked much at how commandline history is implemented, but it does not seem to be implemented in subcommands.  It would be nice to have a flag that forces history to be available to running commands, so that a command could temporarily enable history for itself.

Or, an alternative, when spawning a command, a new temporary history object is pushed to the stack anD used until the command is done.  Then, the original history command is popped.. So only history local to the context (command or stash) is used.

My specific use case:  I often do debugging inside of stash, using Pdb.  The annoying thing about pdb in pythonists is the lack of up/down arrow usage, or history popup.  Allowing history for commands would make debugging at least not quite so painful.

**Comment by ywangd** [comment]
I thought about providing localised history for running commands. But back then I didn't find a very good use case for it. Now the usage of pdb is a great one. I didn't even know its possible. I'll work on it.

**Comment by ywangd** [comment]
This feature is now implemented and pushed to the `dev` branch. Please give it a go and let me know how it works for you.
