### ISSUE TITLE
telnet

### ISSUE THREAD

**Issue by briarfox** [ywangd/stash#98]
@jsbain telnet does not appear to send \r\n only \n I believe telnet usualy sends the < CR >. I'm also unable to get [[[ to quit. telnet is looking good and it's a great addition to stash.

**Comment by briarfox** [comment]
Made the fixes in #99

**Comment by ywangd** [comment]
Rewrote the telnet command to provide true terminal emulation and Ctrl-C for quit.

**Comment by jsbain** [comment]
does telnet://towel.blinkenlights.nl now work?

**Comment by ywangd** [comment]
Yes and you can press Ctrl-C to quit. Honestly I don't have much experience
with telnet. This is mainly a by-product of improving ssh. If you notice
anything abnormal, please let me know.

On Friday, 19 February 2016, jsbain <notifications@github.com> wrote:

> does telnet://towel.blinkenlights.nl now work?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ywangd/stash/issues/98#issuecomment-185827721>.
>


-- 
----------------------------------------------------------------------
                      Life is elsewhere

**Comment by steljas** [comment]
@ywangd @briarfox Is there anyhing outstanding with telnet implementation?
